### ISSUE TITLE
Create Milestones for 2022 

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#1027]
### Overview
Create milestones based on LADOT timeline for the launch of TDM to the public

### Action Items
- [x] Update existing milestones based on the LADOT timelines, add the tentative months for planning
- [x] Create all milestones for 2022 for us to phase out changes after going public
- [x] Create a [spreadsheet](https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit#gid=0) with all the steps for easy updates
- [x] Move Issues to the right milestones for easy planning 
- [x] Review it with the team and Bonnie
- [x] Review with LADOT team

### Resources/Instructions
- https://github.com/hackforla/tdm-calculator/milestones
- [Slides with LADOT and LACP milestones](https://docs.google.com/presentation/d/1Co35UxoPZkD6W26tdB5MK47otd22Bcjs/edit#slide=id.p1) - made by Seena
- [Spreadsheet version of the LADOT and LACP milestones](https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
Add additional milestones that match the slide deck, and number them 01 onward.

**Comment by seenaiype** [comment]
Create the spreadsheet - https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit#gid=0

**Comment by ExperimentsInHonesty** [comment]
freeze prod 2022-06-07
push all accepted UAT changes to prod on 2022-08-13
freeze prod on 2022-09-12
