### ISSUE TITLE
About Us page - add the checklist of resources for the TDM calculator

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#1080]
### Overview
 Add the checklist under Additional resources in the About-Us page

### Action Items

- [ ] As part of #875 , add the list of resources also to the About Us page
- [ ] Update the design for the "About Us" page
- [ ] Review the design with LADOT
- [ ] Create the dev ticket to make updates on the page

### Resources/Instructions
#875
