### ISSUE TITLE
Checklist popup for the create project page

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#1086]
### Overview
To provide some guidance on the information users that would be helpful for the calculator, we are going have a pop-up show with the list of required information and information around exemption 

### Action Items
- [x] Popup to show to all users doing a new project
- [x] popup shall showup only on the first page
- [x] add a link to the footer of the page, for easy access to the popup 
- [x] Popup for checklist shall be visible after the terms and condition
- [x] popup shall show for both logged in and not logged users
- [ ] To be reviewed with the product team
- [ ] To be reviewed with the stakeholders
- [x] Add wording  "Check LAMC Section 12.26 J.3(b)(3) of the **Draft Revised TDM Ordinance** for exemption details."
       - 

### Resources/Instructions
[Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5683%3A20479)
#693 - terms and condition story, to make sure we do this in co-ordination

**Comment by jahpe777** [comment]
@seenaiype @KPHowley - Should the modal close simply by clicking the "X" **only** or should it **also close** if you click outside of the modal?

1. Progress: I have the basic structure in place. Finalizing styling. Click events need to be completed. Local storage needs to be completed
2. Blockers: May want help with events
3. Availability: Somewhat available
4. ETA: March 30th

**Comment by jahpe777** [comment]
Finalized checklist modal 
![Screen Shot 2022-03-20 at 2 22 37 PM](https://user-images.githubusercontent.com/40730303/159186525-0e3c059c-cc53-4c85-a3bc-5cda17a3c68b.png)

**Comment by jahpe777** [comment]
Updated styling and fixed relationship between Terms and Conditions modal and Checklist modal
