### ISSUE TITLE
User Testing 2: Create and Organize Issue Tracker

### ISSUE THREAD

**Issue by Jane4925** [hackforla/tdm-calculator#1150]
### Overview
Create Issue Tracker spreadsheet containing all pain points/issues/feedbacks found from user testing round 2 (April 2022) as the basis for creating issues in GitHub.

### Action Items
- [x] Review all items listed in the Resources down below if available 
- [x] Identify problems and organize them into following items to fill in [issue tracker spreadsheet](https://docs.google.com/spreadsheets/d/1SWcf55uRkXV41uCMTp7VLelAslf6rQCGeyCYXfGzbBU/edit?usp=sharing):
	- Location: where is the problem 
	- Problem overview: summarize the problem
	- Problem description: describe the problem and explain why it is considered as problem, including examples and quotes if applicable
	- Potential solution: outline general approach
	- Priority: how important it is from UX point of view 
- [x] Meet with Bonnie and/or PM team to go over problems and fill in following items: 
  - Action: evaluate problems and actionable items
  - MoSCoW: determine feasibility for upcoming launch
  - Priority: re-evaluate after determining feasibility and MoSCoW
- [x] Hand over issue tracker to PM team to create actionable issues and continue tracking  status :
	- Issue #: create issue on project board
	- Responsibility: HfLA or stakeholder work
	- Assign Team: which team should be working on the issues
	- Status: current progress of the issues 

### Resources/Instructions

- Review items:
  - Interview session recordings
  - Miro board 
  - Analysis spreadsheet: quote and site testing tab    
  - Stakeholder meeting slide decks
  - Stakeholder meeting recordings

**Comment by jarmitageux** [comment]
@Jane4925 Jill updated overview, please review and revise or approve. Is this issue ready to be closed?

**Comment by Jane4925** [comment]
@KPHowley @Biuwa @SMR9220 Issue tracker is up-to-date. UX team is gonna hand it over to PMs and close this issue.
