### ISSUE TITLE
Create Milestones for 2023

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1306]
### Overview
Based on the LADOT timeline, create milestones for public launch of TDM

### Action Items

- [ ] Update existing milestones based on the LADOT timelines, add the tentative months for planning
- [ ]  Create all milestones for 2023 for us to phase out changes after going public
- [ ] Update  [spreadsheet](https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit#gid=0) 
- [ ]  Move Issues to the right milestones for easy planning
- [ ]  Review it with the team and Bonnie
- [ ]  Review with LADOT team

### Resources/Instructions
https://github.com/hackforla/tdm-calculator/milestones
[Slides with LADOT and LACP milestones]
[Spreadsheet version of the LADOT and LACP milestones](https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit#gid=0)
