### ISSUE TITLE
Epic: Identify Security Standards 

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1364]
### Overview
We need to identify what security standards we should be adopting

### Action Items
- [ ] Review OWASP Security standards
- [ ] Meet with DevOps community of practice to 
   - [ ] find people who want to help us figure out how to test this code base and write up practical guidance for future features that are added to the site.
   - [ ] define tests we should be running, ongoing
- [ ] Evaluate if we are currently meeting the security standards below.

### Resources/Instructions
https://owasp.org/search/?searchString=Standards
- [x] [A01:2021-Broken Access Control](https://owasp.org/Top10/A01_2021-Broken_Access_Control/) 
- [x] [A02:2021-Cryptographic Failures](https://owasp.org/Top10/A02_2021-Cryptographic_Failures/) 
- [ ] [A03:2021-Injection](https://owasp.org/Top10/A03_2021-Injection/) - city has sent us some failure reports for these
- [ ] [A04:2021-Insecure Design](https://owasp.org/Top10/A04_2021-Insecure_Design/) 
- [ ] [A05:2021-Security Misconfiguration](https://owasp.org/Top10/A05_2021-Security_Misconfiguration/) 
- [x] [A06:2021-Vulnerable and Outdated Components](https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/) - update dependencies
- [ ] [A07:2021-Identification and Authentication Failures](https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/) - city has sent us some failure reports for these
- [ ] [A08:2021-Software and Data Integrity Failures](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/) 
- [ ] [A09:2021-Security Logging and Monitoring Failures](https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/) 
- [ ] [A10:2021-Server-Side Request Forgery](https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/)

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide 1364](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g3389954eb7d_9_42)
- Release Deck
   - [YYYY-MM-DD Release Deck, slide 1364]

**Comment by Biuwa** [comment]
This is a Stakeholder walkthrough

**Comment by hi-tek-low-life** [comment]
I'm happy to take a look at these things.

**Comment by ExperimentsInHonesty** [comment]
@hi-tek-low-life Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by ExperimentsInHonesty** [comment]
@hi-tek-low-life Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by ExperimentsInHonesty** [comment]
@ale210 do you know hi-tek-low-life?  He needs to provide an update on his issue and he has not. If you don't know him
- [ ] unassign him from the issue
- [ ] move it to new issue approval column
- [ ] remove the `ready for DEV Lead-OPS label
- [ ] add the ready for prioritization label

**Comment by lola3736** [comment]
@entrotech it appears no response from @hi-tek-low-life, for over 2weeks.  Can we reassign?

**Comment by Bwoltz** [comment]
@angelaliao1231

1. Progress: I have some ideas for a few of these points, but wanted clarification
2. Blockers: I have [questions above](https://github.com/hackforla/tdm-calculator/issues/1364#issuecomment-2982075663)
3. Availability: Evenings on weekdays and all day weekends
4. ETA: None
5. Pictures: None

**Comment by Rabia2219** [comment]
@Bwoltz Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

You can use this template
```
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary): 
```

**Comment by Rabia2219** [comment]
@Bwoltz 

Can you please give an update on where we are on this issue? Do you have any questions for the stakeholders and will you be attending the next meeting with them?
Any information you can provide would he helpful. Thanks.

**Comment by Benettonkkb** [comment]
# Action Item: Review OWASP Security standards

## TLDR;
References above are obsolete; new OWASP standard identifies completely new critical concerns. While not all OWASP-10 threats apply to TDM, current open Issue coverage doesn't comprehensively address high-priority vulnerabilities. Bump in supply chain targeting threatens some options for "hand it over to non-technical owners" possibilities. Path forward to standards identification and security testing is clear. 

## Overview
I had a suspicion that the OWASP Top 10 standards from the references above were outdated, and was able to determine that to be exactly the case. **The OWASP Top 10 updated in late 2025**- and to a significant departure from the 2021 standards provided above. 

From [Parasoft](https://www.parasoft.com/blog/owasp-top-10/):
<img width="499" height="765" alt="Image" src="https://github.com/user-attachments/assets/ee0da48f-1502-4baf-8e7c-15d77c860f09" />

**The most relevant amongst these changes impacting TDM**:
- _Broken Access Controls_ category stays at A01, but the _Server-Side Request Forgery_ exploit vector, originally being lower-priority at A10 above, get's rolled in to the former- becoming a top-priority vulnerability. 
- _Security Misconfigurations_ moved from A05 to A02, which is of heightened concern, as we intend on handing the app over to non-technical owners. I have thoughts and solutions to this below. 
- Two **new categories** were added: _Software Supply Chain Failures_(of particular importance to us), and _Mishandling of Exceptional Conditions_.

## OWASP(for those who may not know)

The [Open Worldwide Application Security Project](https://owasp.org/) (OWASP) is a non-profit org of developers and security people who make data-informed, industry-defining advisories for various information security needs- Internet of Things, mobile, and their most well-known framework- the [OWASP Top 10](https://owasp.org/Top10/2025/), which is for web applications. They collect data on real-world attacks on live web apps and establish threat criticality for various web app attack vectors based on a sort of "scope and severity" calculation. 

## The 2025 Top 10 and where TDM is currently 

| 2025 Standard | 2021 Standard | Applies to TDM (React/Express)? | Existing issue(s) | Assessment type | Priority before ship |
|---|---|---|---|---|---|
| A01 Broken Access Control (incl. SSRF) | A01 + A10 | Yes | [Issue 2831: Admin Access Controls](https://github.com/hackforla/tdm-calculator/issues/2831) [Issue 2676: Scoped email domains for high-priv accounts](https://github.com/hackforla/tdm-calculator/issues/2676) [Issue 2847 Instantiate Account Expiry](https://github.com/hackforla/tdm-calculator/issues/2847) [Issue 2857: Consistent Privilege Validation and Denial](https://github.com/hackforla/tdm-calculator/issues/2857) | Code review & local pentest | High |
| A02 Security Misconfiguration | A05 | Yes; for untended deploy | [Issue 2688: Implement CSP](https://github.com/hackforla/tdm-calculator/issues/2688) [Issue 3264: Insecurity HTTP Headers](https://github.com/hackforla/tdm-calculator/issues/3264) | Config/code review, CI, pentest | **High** |
| A03 Software Supply Chain Failures | A06 (expanded) | Yes | _[Need Investigation]_ | CI / dependency review (low manual) | **High** |
| A04 Cryptographic Failures | A02 | Yes | _[Need Investigation]_ | Code review(scanners) | Medium |
| A05 Injection | A03 | Yes | [Issue 2661: Injection](https://github.com/hackforla/tdm-calculator/issues/2661) | Code review & local pentest | Medium–High |
| A06 Insecure Design | A04 | Partial | #1364 (this Issue) | Threat-modeling; arch review | Low at first |
| A07 Authentication Failures | A07 (renamed) | Yes | Historical closed work exists (e.g. #412 JWT-on-logout, fixed by #1583); _confirm current open items_ | Code review & local test | Medium |
| A08 Software/Data Integrity Failures | A08 | Yes | _[Need Investigation]_ | CI & build review | Medium |
| A09 Logging & Alerting Failures | A09 (renamed) | Yes; but new owners won't be watching | _[Need Investigation]_ | Doc & design | Likely handoff doc |
| A10 Mishandling of Exceptional Conditions | (new) | Yes | _[Need Investigation]_ | Code review/Input Validation | Medium |

Additional security-oriented Issues which may need inquiry, revisiting, or review for redundant state:
[Issue 687: Determine Security testing needs](https://github.com/hackforla/tdm-calculator/issues/687)
[Issue 1360: Suspicious and malicious logins](https://github.com/hackforla/tdm-calculator/issues/1360)

## Next Steps - Goals 
- [x] (by 6/10/2026 Meeting) Identify all CWE vectors applicable to TDM app
  - [x] (by 6/10/2026 Meeting) Review open and closed Issues which address CWEs for comprehensive remediation 
  - [ ] Propose Issues for un-addressed vulnerabilities, based on plausibility of completion before shipping
- [ ] Finalize tool selection for web app security scanning 
<img width="1474" height="339" alt="Image" src="https://github.com/user-attachments/assets/1e23d04e-617f-416f-835a-d608e82cae2b" />

- [ ] Propose testing process with team

**Comment by ExperimentsInHonesty** [comment]
- [ ] Create issue to fix references where it should be dateCreated but is date_created  
   - Incorrect usage
      - https://github.com/hackforla/tdm-calculator/blob/6df106db3f92ff762605f3beb92a49e1a633ab54/server/app/services/account.service.js#L309
   - Correct usage examples can be found in 39 files [code search: dateCreated](https://github.com/search?q=repo%3Ahackforla%2Ftdm-calculator+dateCreated&type=code)
      - https://github.com/hackforla/tdm-calculator/blob/6df106db3f92ff762605f3beb92a49e1a633ab54/client/src/components/Feedback/ProjectList.jsx#L110

**Comment by Benettonkkb** [comment]
- [ ] Create issue to give one uniform response when submitting email.
    - **Risk**: This issue enables email enumeration attacks via crafted requests
    - Problem Current State:
        - https://github.com/hackforla/tdm-calculator/blob/d1fc35486b2164761e1f0e833e3ed49881bd42d9/server/app/services/account.service.js#L223-L242
    - Solution:
        - Remove `message: ...` lines from condition statement
        - One singular `message: ...` line after check, independent of outcome: "If this email is registered to an account, a password recovery email will be sent."
