### ISSUE TITLE
EPIC: Create Style Guide Presentation

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1365]
### Dependency
- https://github.com/hackforla/tdm-calculator/issues/1721
- https://github.com/hackforla/tdm-calculator/issues/1725
- https://github.com/hackforla/tdm-calculator/issues/1727
- https://github.com/hackforla/tdm-calculator/issues/1687
- https://github.com/hackforla/tdm-calculator/issues/1768
- #1839 
- #1843 
- #1998 

### Overview
We need to create a Google deck of all the style guide pages on Figma and add a link to the wiki

### Action Items

- [x] Create Deck using the [presentation format](https://github.com/hackforla/tdm-calculator/wiki/Style-Guide#:~:text=calculator.wiki.git-,Presentation%20Format,-Add%20a%20custom)
- [ ] Review with the team and PMs
- [ ] Add a link to the style guide section of the wiki

### Resources/Instructions
- [Google Slides Style Guide Presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)
- [Link to style guide in Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619-11671&mode=design&t=oSV4Vrfj1WvuN2Rw-0)
- [presentation format](https://github.com/hackforla/tdm-calculator/wiki/Style-Guide#:~:text=calculator.wiki.git-,Presentation%20Format,-Add%20a%20custom)
- [Wiki](https://github.com/hackforla/tdm-calculator/wiki#:~:text=Team%20Meetings-,Style%20Guide,-Add%20a%20custom)

#### Slides
- not for stakeholder

**Comment by Biuwa** [comment]
@Noushie I know your team is currently busy with the My Projects page, so I'll be unassigning this issue and moving it to the prioritized column. it is ready to be worked on.

**Comment by ShahAmani** [comment]
Update:

I completed this deck
[LADOT TDM Style Guide.pdf](https://github.com/hackforla/tdm-calculator/files/13233299/LADOT.TDM.Style.Guide.pdf)

I did not realize I should be using the 'presentation format' above. I will revise the slides using the correct format

**Comment by ShahAmani** [comment]
Question:

**Which design system should I be referencing?** 

[This one](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?type=design&node-id=103-0&mode=design&t=kOw0fepRM9AHIgbq-0) or [this one](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619-11671&mode=design&t=CrAk4VZNyngGtbqV-0)?  

Each figma file has different typography and color palettes. Plus the first file does not include components.

**Comment by Biuwa** [comment]
@ShahAmani The new Design System: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619-11671&mode=design&t=oSV4Vrfj1WvuN2Rw-0

**Comment by ShahAmani** [comment]
Hello @Biuwa , 

Can you please review my Style Guide Presentation and provide feedback on if it is ready to be approved?

Please go to [slide 3](https://docs.google.com/presentation/d/1p1AKZbLSeYmCOsc9O0SYkRo_dEsh70vA5qdKuz0EPKw/edit#slide=id.g298706b2fee_0_0), and select the first link “[Style Guide Presentation - link](https://docs.google.com/presentation/d/1vBR0Gmj6Vynx_VUS7wcJ3DC0bcBcBOFIMSsJqqFrChU/edit#slide=id.g25e7582e081_0_0)”

Looking forward to hearing back.

**Comment by Biuwa** [comment]
- Shah, Apologies for the late reply, but i cannot access the link you provided: [Style Guide Presentation - link](https://docs.google.com/presentation/d/1vBR0Gmj6Vynx_VUS7wcJ3DC0bcBcBOFIMSsJqqFrChU/edit#slide=id.g25e7582e081_0_0)
- Please move the file to the [TDM shared drive ](https://drive.google.com/drive/folders/1xbZQX8FvRh-DdFw20baJQ8wAwU9quNp4)

**Comment by ShahAmani** [comment]
@Biuwa I uploaded the file to the TDM Shared Drive. 
It was uploaded into the location: TDM calculator> UIUX > Design > Sidebar images
I dont have the ability to move it from that location in the shared drive but here is the [link](https://drive.google.com/file/d/1oYwn7dm5ouAlrWOVVsLIMk0AEUBAYYE-/view?usp=drive_link)

**Comment by ShahAmani** [comment]
Hi @Biuwa 

Here is the updated Presentation: 
[LADOT TDM Style Guide Presentation.pdf](https://github.com/hackforla/tdm-calculator/files/13372274/LADOT.TDM.Style.Guide.Presentation.pdf)

It can also be found in the [TDM Shared Drive](https://drive.google.com/drive/folders/1kWindzCvAqyDNTiW057HF5C0yErl_mHZ) under the file name: LADOT TDM Style Guide Presentation

I added the Hack for LA logo on each page. Let me know if any changes should be made.

**Comment by yiranshan** [comment]
--- Don't use the iconography on the current front and back page. refer to this deck for styling: [2024-04-16 Release Updates](https://docs.google.com/presentation/d/1NoDxeIDm0SbSrOBbpiMFk1kniakbFO8QHatlIbFlRmA/edit#slide=id.g16124103adf_0_0)
--- Add an extra page similar to this (with link to the [Figma Page](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=2619-11671&mode=design&t=hS67MStEZOYuk7KI-0)):
<img width="1665" alt="Screen Shot 2024-04-11 at 4 34 05 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/b09bcdb7-9b05-4158-8f74-35b17a6164b1">

**Comment by ExperimentsInHonesty** [comment]
- We don't need to put the pages into a google slides, since they are in figma and can be edited there.  Also, this preserves the fonts, that may not be available in Google Slides
- We do need to update the pdf with proper beginning and ending slides
   - [beginning slide example ](https://docs.google.com/presentation/d/1NoDxeIDm0SbSrOBbpiMFk1kniakbFO8QHatlIbFlRmA/edit#slide=id.g1443c52839c_0_2)

**Comment by ShahAmani** [comment]
Hello,
Here is the updated presentation: 

[Style Guide Presentation (4_24_24).pdf](https://github.com/hackforla/tdm-calculator/files/15105376/Style.Guide.Presentation.4_24_24.pdf)

Looking forward to your feedback. Thank you

**Comment by Parisajf** [comment]
In the last slide: 
We need to add the Dev site and production site, and other links and references
Dialog boxes needs to match the Figma

**Comment by ExperimentsInHonesty** [comment]
Please 
- [ ] add the link to the current Figma page for this style guide to the top of the issue.  The current one seems out of date.  
- [ ] Also add the link for the Google Slides recent version to the top of the issue under resources.

**Comment by ExperimentsInHonesty** [comment]
@ShahAmani 
Please provide update.  Is there a new version of the deck.  Are you finished, etc?
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ShahAmani** [comment]
The most updated version of the deck is linked under resources.

1. Progress: 
    - This issue is still in progress. 
    - Left to do: 
        - Design team must perform UI audit to update/validate Figma Style Guide
        - Issue 1687 - contingent on this issue

3. Blockers:
    - The slide deck is reflective of the Figma Style Guide. The information on the Figma Style guide and the website do not match. For example, dialog boxes and buttons are not consistent. 
    - All icons need to be replaced (Issue 1687)

4. Availability: 
    - I will have about 4 to 6 hours this week to work on this issue.

5. ETA: 
    - I expect this issue to be completed in about two weeks. (about one week for the ux team to perform an audit of all design elements of the website and one week to replace all the icons)

Questions:
    Should the Style Guide Deck be based of the Figma Style Guide or the website? Because they do not match. 
Aka whats the source of truth- Is the website based off the Figma Style Guide or is the Figma Style Guide based off the website?

**Comment by yiranshan** [comment]
1. Progress: cleaning up style guide
2. Blockers: some questions regarding icons, refer to issue[ #1687](https://github.com/hackforla/tdm-calculator/issues/1687)
3. Availability: most team members should be able to spend 2-4 hours
4. ETA: next week
<img width="565" alt="Screen Shot 2024-05-23 at 3 16 38 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/99749031-7440-421f-b39a-43c92a50b208">
<img width="766" alt="Screen Shot 2024-05-23 at 3 16 21 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/51472583-1e64-4e3e-bd05-74e3d7eb92f0">
<img width="877" alt="Screen Shot 2024-05-23 at 3 16 02 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/539e1dcc-faed-4e9e-90ee-9a95a8b34b15">
<img width="877" alt="Screen Shot 2024-05-23 at 3 15 54 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/c649c7b6-6fd7-4757-b2de-b40ebe35c34d">
<img width="454" alt="Screen Shot 2024-05-23 at 3 17 33 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/12c5988f-e2cc-4b79-9922-174c6be51a25">
<img width="601" alt="Screen Shot 2024-05-23 at 3 17 26 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/13f0611b-7137-4d3d-a09c-9250ecc24635">
<img width="463" alt="Screen Shot 2024-05-23 at 3 17 07 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/026fc8a2-0efa-4e32-8e2c-df7ad03eb1b5">
<img width="455" alt="Screen Shot 2024-05-23 at 3 17 00 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/dd10fdb1-b03d-4a61-837e-a85662864ea8">
<img width="456" alt="Screen Shot 2024-05-23 at 3 16 54 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/19a9bd4c-f85c-488a-a71f-1e858cf6a048">
<img width="457" alt="Screen Shot 2024-05-23 at 3 16 46 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/c0848614-1c30-4d40-a38c-07101af3c6b6">

**Comment by yiranshan** [comment]
here is a list of members who worked for each section, not sure if we can add everyone to the issue: 
Design System Clean Up:
Color Palette @lbeatonn 
Iconography @marlenamellody 
Buttons/Pagination @ShahAmani (delayed to next week)
Dialog Boxes, Modals, Accordians Tabs, Tooltips @yiranshan 
Text Inputs/Fields @namigoeku

**Comment by ExperimentsInHonesty** [comment]
Emily's comments
- Are tool tips in the Paragraph 1 style?
- add hex code in text
  - bonnie provided an example https://docs.google.com/presentation/d/1b67e6ubqqKgFTf7l1A9srHDrCEIk5kprRf9JldS5RNI/edit#slide=id.g8078b36bb8_0_0
- 11: At the top of the 2nd column, the "Edit Section" button is a style that we don't see outlined on the left of this slide. Please make sure there's an explanation of when to use that style, too.
  - Bonnie added a circle.  There are variations in the examples that should be in the Button Types with details about when to use each

**Comment by ExperimentsInHonesty** [comment]
[Copy of GYR Communications Guide for Document Creation [INTERNAL] - COLORS SLIDE](https://docs.google.com/presentation/d/1b67e6ubqqKgFTf7l1A9srHDrCEIk5kprRf9JldS5RNI/edit#slide=id.g8078b36bb8_0_0)

**Comment by yiranshan** [comment]
creating sub issues to divide this issue:
https://github.com/hackforla/tdm-calculator/issues/1721

**Comment by NilakshiS** [comment]
By @Parisajf 
Buttons:

We need to update the buttons and the use cases.

The use of the tertiary button (when it has a green outline), is for when there are two positive buttons on the same page, the outline version is less important option)

![Screen Shot 2024-06-20 at 4 04 30 PM](https://github.com/hackforla/tdm-calculator/assets/134427433/a51791b9-e185-489b-a4a7-fafbb6bd18a3)

Style Guid Slides:
https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g27275e02f73_6_0
https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2e134a56948_6_41

**Comment by Rabia2219** [comment]
> [!NOTE]
> NOT in staging deck as of 2025-05-07 and I am not sure it belongs there...please review...
