### ISSUE TITLE
Product: Epic: Create a website Page Features Reference

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1485]
### Overview
We need to create a document for the project to be added to the GitHub wiki. This document will outline the features of each page on the website we are working on, with the  purpose of aiding future developers

### Action Items
- [x]  Add a list of all pages from the TDM calculator website to the wiki page, Website pages
   - [x] Add that same list into a comment on this issue
- [x] Create a new wiki page for each page of the website using the template and write the purpose for the page
- [x] Link the new pages, to the wiki page, Website Pages
- [x] Create new issues for each of the wiki pages for each practice area to fill in with details
   - [x] Dev
   - [x] Design

### Resources/Instructions
- TDM Calculator website, DEV: http://tdm-dev.azurewebsites.net/
- wiki page, Website Pages: [Product Documentation](https://github.com/hackforla/tdm-calculator/wiki/Product-Documentation) - this will have links to separate wiki pages for each page on the site.
- [TDM Website Page Features Reference](https://docs.google.com/document/d/14TyswHlu4RM_IruxTnYslOb9-Aq6yHhhQNv5VF2eJT8/edit?tab=t.0)

#### Template
```
Page Name
### Purpose of page
- 
- 

### URLS
- Dev URL: http://tdm-dev.azurewebsites.net/[Replace with PAGE URL NAME]
- Prod URL: https://tdm.ladot.lacity.org/[Replace with PAGE URL NAME]
- GitHub location: 
- Figma Design: 

### Issue label
- Issue Label on Issue tab: [p-feature: ????]
- Issue label on Project Board: [p-feature: ????]

### Screen shots of page

### Technical Details
[Add details that any developer would need to know.  e.g., what end points does it use, how does it interact with scripts, etc.]
```

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide 1485](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g34e1369e71a_0_0)
- Release Deck
   - [YYYY-MM-DD Release Deck, slide 1485]

**Comment by ExperimentsInHonesty** [comment]
Add these items to the Navigation page
### Header
  - LADOT
  - City Services
  - City Directory

**Comment by maulieshah** [comment]
# List of all the wiki pages from the TDM Calculator website:
Technical and Product Documentation

#### App Documentation
* User Roles
* Calculation Engine

#### Pages/elements on the website
* Login
  * Registration and Login
  * Update Account
  * Forgot Password
* My Projects
* Create Projects
* About
* Security
* FAQ
* Feedback
* Terms and Conditions
* Privacy Policy
* Checklist
* Navigation

**Comment by ExperimentsInHonesty** [comment]
@maulieshah 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
@maulieshah Please provide update 
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
@maulieshah Make all the dev issues for them to fill out the pages.  And leave a comment with the links, and anything else that needs to be done.

**Comment by maulieshah** [comment]
Create different Wiki pages for all the TDM website feature and created new issues for dev and design team to update the techinical details into those pages.

**Comment by ExperimentsInHonesty** [comment]
Use this string to find issues and add them as sub issues
```
Update WIKI with technical details
```

**Comment by ExperimentsInHonesty** [comment]
Check issues under [label feature: product documentation](https://github.com/hackforla/tdm-calculator/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22feature%3A%20Product%20Documentation%22%20)

**Comment by londondkim** [comment]
@ExperimentsInHonesty Bonnie, I see that this wiki page is already up and running + all the check boxes are checked off. Is this project considered done?

**Comment by ExperimentsInHonesty** [comment]
@londondkim 

>@ExperimentsInHonesty Bonnie, I see that this wiki page is already up and running + all the check boxes are checked off. Is this project considered done?

No, which is why I updated this spreadsheet for you Draft Spreadsheet [TDM Issue #1886](https://docs.google.com/spreadsheets/d/1YCxgnALyOmiCrTOc5IepveS_-7zo0xQ0SdWd8RI7Bqw/edit?gid=0#gid=0)

**Comment by ExperimentsInHonesty** [comment]
@kcoronel the list on the product documentation link is not current. See Draft Spreadsheet [TDM Issue #1886](https://docs.google.com/spreadsheets/d/1YCxgnALyOmiCrTOc5IepveS_-7zo0xQ0SdWd8RI7Bqw/edit?gid=0#gid=0) for a current and future list of pages and their URLs.  Add anything that is working and add a note at the bottom of the page about things that their names and URLs are in flux

**Comment by ExperimentsInHonesty** [comment]
@kcoronel Please provide a new ETA

**Comment by kcoronel** [comment]
Hi everyone! New ETA is Saturday 4/26.

**Comment by ExperimentsInHonesty** [comment]
@kcoronel Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by kcoronel** [comment]
Duplicate issue? https://github.com/hackforla/tdm-calculator/issues/2302

**Comment by kcoronel** [comment]
@ExperimentsInHonesty 

> Reviewed the[pages for the website and made comments on what was missing/flux](https://docs.google.com/spreadsheets/d/1YCxgnALyOmiCrTOc5IepveS_-7zo0xQ0SdWd8RI7Bqw/edit?gid=0#gid=0)

What does flux mean

>> using your verbiage from this comment (I read it as anything that looks weird) 

<img width="795" alt="Image" src="https://github.com/user-attachments/assets/330fd376-2c8b-4a4e-b15a-e8b426433021" />

**Comment by ExperimentsInHonesty** [comment]
@kcoronel one of the developers thought that the wiki issue they were supposed to work on was just one page, but it's multiple pages within that one menu item.  
- Example from this issue is the Login page (which also has lost password, etc.) https://github.com/hackforla/tdm-calculator/issues/1861#issuecomment-2846080497 
   - login is the menu item: https://github.com/hackforla/tdm-calculator/wiki/Registration-and-Login
     - Update Account is only accessible through Login: https://github.com/hackforla/tdm-calculator/wiki/Update-Account
     - Forgot Password is only accessible through Login:https://github.com/hackforla/tdm-calculator/wiki/Forgot-Password

Make sure there are separate issues for each page

**Comment by lola3736** [comment]
@kcoronel 
Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by ExperimentsInHonesty** [comment]
@kcoronel Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

You can use this template
```
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary): 
```

**Comment by ExperimentsInHonesty** [comment]
@gabcdominic we need a template so that the pages come out basically the same.  This is the start of that (I based it off the My Project's page.  Please look through the pages that have been completed and figure out if there is any other info that might be included.

### [NAME OF PAGE]
- [DETAILS]
- [DETAILS]

#### FEATURES
- [DETAILS]
- [DETAILS]

### URLS
- Dev URL: 
- Prod URL: 
- GitHub location: 
- Figma Design: 
  - WIKI [TDM Calculator Figma Pages and Structure](https://github.com/hackforla/tdm-calculator/wiki/Figma) 
  - Figma [TDM Calculator Figma Pages and Structure, User-Facing Screens]
  - Figma [TDM Calculator Handoff, User-Facing Screens]
  

### Issue label
- [label:"p-feature: [PAGE NAME]" on Issue tab]
- [label:"p-feature: [PAGE NAME]" on Project Board]

### Screen shots of page


### Technical Details


### Files that mention Checklist and how they interact

#### Core Files


#### Other files

**Comment by Rabia2219** [comment]
#### Do not have the new template
- https://github.com/hackforla/tdm-calculator/issues/2674
- https://github.com/hackforla/tdm-calculator/issues/2680
- https://github.com/hackforla/tdm-calculator/issues/2681

**Comment by ExperimentsInHonesty** [comment]
@gabcdominic 

Your question
> Compared [TDM Audit Wiki Pages for Screenshot Completeness Issue 2649](https://docs.google.com/spreadsheets/d/1tk2rRk3n0GXWPuBdSdujjlQxkwrHqZHxSlcYJBJFJxQ/edit?gid=0#gid=0) and [TDM Issue 1886 ](https://docs.google.com/spreadsheets/d/1YCxgnALyOmiCrTOc5IepveS_-7zo0xQ0SdWd8RI7Bqw/edit?gid=0#gid=0).
> 
> The [old spreadsheet ](https://docs.google.com/spreadsheets/d/1YCxgnALyOmiCrTOc5IepveS_-7zo0xQ0SdWd8RI7Bqw/edit?gid=0#gid=0)tracked the use of "#", "Number", and "No." Is this still relevant? Do we want to add a column in the new spreadsheet for "Global Notes" section to audit all pages for consistent use of "Number" over symbols like "#?

A: We created the issue to fix the # vs No. issue.  So I don't think we need to track it again.  
- https://github.com/hackforla/tdm-calculator/issues/3175

---

I think now is a good time to update your spreadsheet.  Most of the pages have been created and here is a list of open issues.  

Update a specific wiki page or spreadsheet
- #2776 - has dependencies
   - #2774 
   - #2775
- #2681 - has dependencies
   - #1677
- #2888 - has dependencies
   - #2947

Adding specific content to more than one wiki page
- #2920 - in prioritized backlog
- #2304 - in prioritized backlog


Update wiki with Technical details
- #1862 - in prioritized backlog
- #2871 - has dependencies tied to a dev change on the page
   - #2774
- #2870 - has dependencies tied to a dev change on the page
   - #2775

**Comment by ExperimentsInHonesty** [comment]
@gabcdominic Do you want to be offboarded, or are you just away, and if so, till what date?
