### ISSUE TITLE
Dev: Implement a "Tooltip" for adding Links to an Answer on the FAQ Admin Screen.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1503]
### Overview
The FAQ Admin screen seems to be working well. However, some feel that the user needs additional instructions for how to enter a hyperlink to the answer text, so the designers have created prototypes for modifications that might be more helpful to the user in Issue #1479.

### Action Items

**Part 1: Researching**
- [x] Review Issue #1479.  This is asking for a change to the link editing modal that currently uses the default modal provided by Quill (the NPM package for HTML editing).
- [x] Review the Quill documentation and see if it is feasible to replace the default link editing dialog with something different.
- [x] Also see if it is possible to edit a link's "target" attribute so we can achieve the desired behavior for internal ve external links as described below in the Resources section of this description.
- [x] Present findings to the team for further actions and possible  implementation.

**Part 2: Implementation**
- [x] Replace the default link editing dialog with a new "Tooltip" that has space to write external links and select internal pages using a dropdown.
- [x] Add functionality so that both internal and external links can be inserted using the "Tooltip" and ensure that internal links and external links have their appropriate formatting on the webpage.
- [x] Add the feature for the FAQ answers that when an internal link is clicked it will open in the same tab and when an external link is clicked it will open in a new tab.
- [x] Remove the additional "default" tooltip that appears for a text that has a link within the Quill editor as it has some non-functioning parts.

### Resources/Instructions
The links in an answer can be either internal to the TDM website and relative (like /termsandconditions, /privacypolicy, /checklist), or external to the TDM site, like https://cityclerk.lacity.org/lacityclerkconnect/index.cfm?fa=ccfi.viewrecord&cfnumber=15-0719-S19

Ideally, when an internal link is clicked, it would use the same browser instance and tab, and just navigate to the different page within the site.  In HTML, this would be the default behavior if you set the target attribute of an <a> tag to "_self".
When an external link is clicked, we would like the browser to open a new tab for the linked site - equivalent to behavior of an <a> tag with the target attribute set to "_blank".

It is not clear if the Quill HTML editor used by the browser allows the user to effectively set the target attribute.

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - ~[Staging Deck, 1503](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g335badb7e3c_34_6)~
- Release Deck
   - [2025-05-13 Release Deck, slide 1503, 1 of 3](https://docs.google.com/presentation/d/1u7-iTsYgBCimvq1JV8oc9MlFkGd9SepB19b4vciP7kg/edit?slide=id.g3532c50d2e7_1_0#slide=id.g3532c50d2e7_1_0)
   - [2025-05-13 Release Deck, slide 1503, 2 of 3](https://docs.google.com/presentation/d/1u7-iTsYgBCimvq1JV8oc9MlFkGd9SepB19b4vciP7kg/edit?slide=id.g3532c50d2e7_1_9#slide=id.g3532c50d2e7_1_9)
   - [2025-05-13 Release Deck, slide 1503, 3 of 3](https://docs.google.com/presentation/d/1u7-iTsYgBCimvq1JV8oc9MlFkGd9SepB19b4vciP7kg/edit?slide=id.g3532c50d2e7_1_20#slide=id.g3532c50d2e7_1_20)

**Comment by Biuwa** [comment]
**@mark-mxwl**

**Please provide an update:**

1. Progress(What is the current status of your project? What have you completed, and what is left to do):
2. Blockers(Difficulties or errors encountered):
3. Availability(How much time will you have this week to work on this issue):
4. ETA(When do you expect this issue to be completed):
5. Pictures (if necessary)(Add any pictures that will help illustrate what you are working on)

**Comment by mark-mxwl** [comment]
Hi @Biuwa, thanks for checking in. Unfortunately, I have not been able to get started on this issue. My availability is very limited at the moment, so I think it would be best to let someone else take over. I'll un-assign myself, and will return this to backlog.

**Comment by mugdhchauhan** [comment]
I can work on this.

**Comment by mugdhchauhan** [comment]
ETA: EOD 22 April 2025
Availability: Weekdays @ 6 PM - 8 PM (BST) - except this Thursday (17/04/2025)

**Comment by mugdhchauhan** [comment]
## Progress Report

### Progress

- [X] Reviewed issue #1479
- [X] Reviewed Quill documentation
- [X] Desired link behaviour is also possible 

Please see "Pictures/Video" section below.

### Blockers

- I tried with two admin accounts that I have access to but the Quill editor did not show on the FAQ page. There is another admin account that works but I did not have access to it so I have used a workaround to explore the features mentioned in this issue.

### Availability

- Weekdays @ 6 PM - 8 PM (BST) - except this Thursday (17 April 2025)

### ETA

- Ready to demo my findings at next meeting

### Pictures/Video  

<details>
  <summary>Quill Editor Demo</summary>

[![Video]()](https://github.com/user-attachments/assets/9351a656-5d9d-4cd2-945e-a21ae78fc50b)

This example is based on Option 1 which the stakeholders have approved as mentioned in issue #1479. There is space to paste external links and select internal pages using a dropdown. 

</details>

<details>
  <summary>Internal Link Demo</summary>

[![Video]()](https://github.com/user-attachments/assets/00860297-b3fd-453c-be6c-63074d5250ab)

Currently all links (internal or external) open in new tab. The above video shows that an internal link can be opened in the same tab.

</details>

<details>
  <summary>External Link Demo</summary>

[![Video]()](https://github.com/user-attachments/assets/ad256e40-3b32-4f30-b06f-6bf10ef5a637)

The above video shows that an external link can be opened in the same tab.

</details>

**Comment by mugdhchauhan** [comment]
- Not enough time in the meeting on Wednesday 16 April 2025. 
- Presented findings to John on Friday 18th April 2025.

**Comment by mugdhchauhan** [comment]
Presented findings to John on Friday 18th April 2025.

**Comment by mugdhchauhan** [comment]
- After speaking with John, agreed to go ahead with implementation. 
- I am currently working on the implementation

**Comment by ExperimentsInHonesty** [comment]
@mugdhchauhan please provide a new ETA

**Comment by mugdhchauhan** [comment]
## Progress Report

### Progress

- I have completed all the action items in this issue as it stands.
- I can now use the correct admin account for the FAQ page.

Please see "Pictures/Videos" section below.

### Blockers

- The FAQs (category, question and answer) are being saved but need to investigate further why they get moved up when the page is revisited.

### Availability

- Weekdays @ 6 PM - 8 PM (BST)

### ETA

- New ETA for the implementation: 14th May 2025. Just need to resolve the blocker.

### Pictures/Videos  

<details>
  <summary>Adding Internal Link Demo</summary>

[![Video]()](https://github.com/user-attachments/assets/1c7accba-cf43-465e-9578-78903e92c7a7)

The video above shows that the implemented "Tooltip" can be used to add an internal link. The internal link has the correct formatting on the page.

Internal links can be opened in the same tab (shown in the "Screenshots/Videos" section of the previous Progress Update [here](https://github.com/hackforla/tdm-calculator/issues/1503#issuecomment-2811063687)

</details>

<details>
  <summary>Adding External Link Demo</summary>

[![Video]()](https://github.com/user-attachments/assets/36511293-e0dd-43bc-88c3-06a64aaa5d41)

The video above shows that the implemented "Tooltip" can be used to add an external link. The external link has the correct formatting on the page.

External links can be opened in the same tab (shown in the "Screenshots/Videos" section of the previous Progress Update [here](https://github.com/hackforla/tdm-calculator/issues/1503#issuecomment-2811063687)

</details>

<details>
  <summary>Saved FAQ</summary>

![Image](https://github.com/user-attachments/assets/c10d9914-9d8e-4da0-9b6d-be7727de688f)

The contents of the Quill editor are being saved. Currently investigating why the section is being moved up as this section was at the bottom (it was after "Next Steps" and then it goes after "Point System").

</details>

**Comment by mugdhchauhan** [comment]
Resolved blocker - saved FAQ retains position on page revisit

**Comment by mugdhchauhan** [comment]
### Implementation 
- [X] "Tooltip" is implemented for the link button which has space to paste external links and select internal pages using a dropdown
- [X] Both internal and external links can be inserted using the "Tooltip"
- [X] The FAQs are being saved
- [X] Removed another default "Tooltip"
- [X] Internal links open in the same tab
- [X] External links open in a new tab
- [X] Internal links and external links have their appropriate formatting

<details>
  <summary>Screenshot of the implementation</summary>

![Image](https://github.com/user-attachments/assets/1d918a42-75cc-4724-bc9b-9c505423d790)

</details>


<details>
  <summary>Screenshot of the additional "Tooltip"</summary>

![Image](https://github.com/user-attachments/assets/a42419b4-f9a4-48ea-afea-2251b54724fa)

There is also an additional default "Tooltip" that appears when a link is clicked within the Quill editor but the "Edit" and "Delete" are not functional so this default tooltip is now removed.

</details>

### Notes

This issue is like three issues in one. 
- Issue 1 (Research): the action items of this current issue as it stands 
- Issue 2 (Implementation): implementing the "Tooltip"
- Issue 3: updating the logic for FAQs

Issues 1 & 2 are done. 

Issue 3
- Now need to update the FAQ logic to make sure the FAQs stay in their place.
- When new FAQs (category, question and answer) are added they are being saved but when the FAQ page is revisited they are being moved up. This is likely due to the present logic of Category IDs. To resolve this would mean rewriting large parts of the `client/src/components/Faq/FaqView.jsx` file and making changes to its related files.

**Comment by mugdhchauhan** [comment]
- Created PR for the implementation
- A separate issue will be created for the saved FAQ ordering

**Comment by mugdhchauhan** [comment]
- The FAQ ordering has been fixed in this PR #2475
