### ISSUE TITLE
Checklist is too wide and some text has wrong font

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1539]
### Overview
In standardizing the Modal Dialogs, some of the desired formatting of the Checklist content was inadvertently changed.

### Action Items
- [ ] There should be a maximum width on the Checklist contents to about 35em.
- [ ] All fonts should use the site-standard Calibri font family.
- [ ] The newer screen shot below has the correct drop-shadow, square corners and close box icon and position - consistent with the Modal standards for the project.
- [ ] It's not clear what text should be bold, but I'd suggest bold for the "Checklist" title, and everything else in regular font weight.

### Resources/Instructions
Previous (in Production):
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/1d437600-0c18-4ae6-83de-7a6df29971f3)

Current (in Dev)
![image](https://github.com/hackforla/tdm-calculator/assets/9939032/630dde9d-80e9-4d36-8b0e-b1da21c15890)
