### ISSUE TITLE
Update Milestones for 2024

### ISSUE THREAD

**Issue by Biuwa** [hackforla/tdm-calculator#1567]
### Overview
Based on the LADOT timeline, create milestones for the public launch of TDM.

### Action Items
- [x] Meet with LADOT to update existing milestones based on the current timelines, add the tentative months for planning
- [x] Update [milestone spreadsheet](https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit?usp=sharing)
- [x] Update/add milestones for 2025 for HfLA 
- [x]  Move Issues to the correct milestones for easy planning
- [x]  Review it with the team and Bonnie
- [x]  Review with the LADOT team.

### Resources/Instructions
- [GitHub Milestones](https://github.com/hackforla/tdm-calculator/milestones?direction=asc&sort=title&state=open)
- [Spreadsheet version of the LADOT and LACP Milestones](https://docs.google.com/spreadsheets/d/1yzpJqBpOs3Uvq4VYidlMldsYGADAz17ei3WsiMEa_Yk/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Review the changes to the spreadsheet and update the [milestone](https://github.com/hackforla/tdm-calculator/milestones?direction=asc&sort=title&state=open) dates accordingly

**Comment by ExperimentsInHonesty** [comment]
To be reviewed at the next PM meeting.  Please add to agenda

**Comment by amitunikorn** [comment]
@ExperimentsInHonesty : This is ready for review.

**Comment by ExperimentsInHonesty** [comment]
make a new milestone 11.02 for Application Launch Formal Application launch so that training and applications can begin

**Comment by ExperimentsInHonesty** [comment]
Review the issues in the 11.0 and 11.01 and see which ones go into 11.02

**Comment by amitunikorn** [comment]
@ExperimentsInHonesty : Updated the current milestones and milestone spreadsheet. There are few dates missing (11 and 11.01) which will be updated once I have the info.

**Comment by ExperimentsInHonesty** [comment]
@amitunikorn I am closing this issue.  We got enough information for me to finish updating the milestones on the project.  I added several new milestones and reprioritized the issues.
