### ISSUE TITLE
Epic: Implement Submission Features

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1652]
### Dependency
- [x] In order to allow users to submit a calculation to LADOT/LACP for review, they need to have the Submission-Related features identified in design issue #1407 and PM Issue #1447
- [ ] when all the issues in this epic are cleared this issue can be closed.

### Overview
We need to have a way for users to submit snapshots for review by LADOT using a form on the site called Submit Snapshot.  

#### Details
this process will have a charge associated with it, however, we are not going to be implementing that.  Its just go to know because this form is different than the feedback form, which is where they can get help, or leave messages without paying.

### Action Items
- [x] #1655
- [x] #1656
- [x] #1657
- [x] #1658
- [x] #1659
- [x] #2346
- [x] #2445
- [ ] #2424 
- [ ] #2387 
- [x] #2372 
- [x] #2367 
- [x] #2311 
- [x] #2031 
- [ ] #2009 
- [ ] Check the [issues tab, p-feature: Submit Snapshot](https://github.com/hackforla/tdm-calculator/issues?q=state%3Aopen%20label%3A%22priority%3A%20MUST%20HAVE%22%20label%3A%22p-feature%3A%20Submit%20Snapshot%22) for additional issues to confirm this feature has reached MVP

### Resources/Instructions
- [Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?type=design&node-id=1009-1673&mode=design&t=XukQo3N6as4CzG42-0)

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide 1652](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g335badb7e3c_0_72)
- Release Deck
   - [YYYY-MM-DD Release Deck, slide 1652]

**Comment by ExperimentsInHonesty** [comment]
when you are on page 5 and its not a snapshot, when you select Submit, it will prompt you to make a snapshot with the text

 "Only snapshots* can be submitted, would you like to make a snapshot now?" 

CANCEL CONTINUE 

*Snapshots cannot be edited, but copies of snapshots can be.

**Comment by ExperimentsInHonesty** [comment]
<details><summary>Dev Summary Screenshot</summary>
<p>

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/f53d7fca-338f-4d00-81fc-bc9f9eb156ea)


</p>
</details> 

<details><summary>Prod Summary Screenshot</summary>
<p>

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/71b414b0-93ba-4d26-b189-5757e45fe9e4)

![image](https://github.com/hackforla/tdm-calculator/assets/37763229/4e2e133b-b451-460e-bd0f-064283238f1c)


</p>
</details>
