### ISSUE TITLE
Research EPIC: Printing/Downloading PDFs Usability Testing 

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1662]
### Dependency
- [x] Issue to finish documenting the last round of user research
- Following design and dev team issues completed:
   - #1809  - dev team issue
   - #1653 - design team issue
   - #1568 - dev team issue

### Overview
UXR team needs to conduct a usability testing for printing/downloading PDFs on page 5 and the "my projects" page. 

### Action Items
- [x] #2185 
- [x] #2187 
   - [x]  Get Research Plan approved by PMs
- [x] #2186 
- [x] #2392 
   - [ ] Run proposed User Testing script by PMs
- [ ] #2188 
   - [ ] Conduct UXR Team Training
   - [ ] Recruit Interviewees 
   - [ ] Schedule Interviews
   - [ ] Conduct Interviews
- [ ] #2189 
   - [ ] FigJam Board 
- [ ] #2190 
   - [ ] Create Presentation of findings for Stakeholders
- [ ] #2191 

### Resources/Instructions
- [Wiki Documentation](https://github.com/hackforla/tdm-calculator/wiki/RP011-Printing-and-Downloading-PDFs-Usability-Testing)
- [RP011 Research Overview](https://github.com/hackforla/tdm-calculator/wiki/RP011:-Printing-Downloading-PDFs-Usability-Testing) 
- Some items in icebox are waiting for this issue to be attached [when attached, add info here]

**Comment by abbyrivard** [comment]
Some items in icebox are waiting for this issue to be attached

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard The dependency on this issue is
>Issue to finish documenting the last round of user research

I can't remember which research are we waiting for documentation?   Is it one of these?  if so which one?  or is it some other research?

https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-Overview

**Comment by abbyrivard** [comment]
Updated all sub-issues/tasks for this epic - moved to prioritized backlog as there are no dependencies.
