### ISSUE TITLE
Research EPIC: Usability Testing - My Projects page 

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1663]
### Dependency
- #1914
- #1915
- #1683 (maybe we don't hold for this issue. It may get developed later)

### Overview
We need to identify all the work to be done for the general usability testing on the "My Projects" page for End Users (not including Admins) so that we can establish timelines and coordinate the work.

### Action Items
Create Issues
- [x] #1937
- [x] #1711
   - [x] Get Research Plan approved by PMs
- [x] #1923
- [x] #1712
   - [x] Run proposed User Testing questions by PMs
- [x] #1714
   - [x] Conduct UXR Team Training
   - [x] Recruit Interviewees 
   - [x] Schedule Interviews
   - [x] Conduct Interviews
- [x] Conduct Data Analysis on My Projects page
   - [x] FigJam Board 
- [x] Create Presentation of findings about the My Projects page for Stakeholders
   - [x] Integrate presentation into stakeholder slide deck
- [x] #1715

### Resources/Instructions
- https://github.com/hackforla/tdm-calculator/issues/888

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard @melissaperry09 This issue needs to be considered an epic, which upgrades its milestone to 03 Project Management.  Then from this issue you will create issues.

**Comment by abbyrivard** [comment]
Create new issue for the following and make issues the dependencies on #1714
   - [ ] Prepare the Training Deck for My Projects Page
   - [ ] Recruit interviewers for My Projects Page
   - [ ] Deliver the training for My Projects Page

**Comment by amiteshsrivastava11** [comment]
Moving this to new issue approval since all the dependencies are completed.
