### ISSUE TITLE
Research EPIC: Download Project to CSV File Usability Testing

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1664]
### Dependency
- #1344
- #1711   

### Overview
We need to identify all the work to be done for the general usability testing on the downloading a project to a CSV file from the My Projects page so that we can establish timelines and coordinate the work.

#### Details
Research on downloading a project to a CSV file, will need to include both with and without (download all) filters applied to ensure users understand the process as it currently is designed.

### Action Items
- [x] #1964
- [x] #1965
   - [x] Get Research Plan approved by PMs
- [x] #1966
- [x] #2452
   - [x] Run proposed User Testing questions by PMs
- [x] #1969
   - [x] Conduct UXR Team Training
   - [x] Recruit Interviewees 
   - [x] Schedule Interviews
   - [x] Conduct Interviews
- [x] #2093
   - [x] FigJam Board 
- [x] #2094
   - [x] Create Presentation of findings from Download Project to CSV File for Stakeholders
- [x] #1967
      - [Wiki Documentation](https://github.com/hackforla/tdm-calculator/wiki/RP006-Download-Project-to-CSV-File-Usability-Test)

### Resources/Instructions

[Wiki](https://github.com/hackforla/tdm-calculator/wiki/RP007-Download-Project-to-CSV-File-Usability-Test)
[RP007 Research Overview](https://github.com/hackforla/tdm-calculator/wiki/RP007:-Download-Project-to-CSV-File-Usability-Test)

<details><summary>Design of the download button</summary>
<p>
- Also can be seen on the issue (#1641 )
<img width="1559" alt="Screen Shot 2024-04-11 at 4 49 48 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/3af4eb9f-1bab-487a-90e0-32e136332d48">
</p>
</details>

**Comment by yiranshan** [comment]
Design of the download button: Also can be seen on the issue (#1641 )
<img width="1559" alt="Screen Shot 2024-04-11 at 4 49 48 PM" src="https://github.com/hackforla/tdm-calculator/assets/79798670/3af4eb9f-1bab-487a-90e0-32e136332d48">

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by abbyrivard** [comment]
1. Progress: This testing has not been started yet.
2. Blockers: Finishing Reset Button analysis and determine priority of this testing.
3. Availability: I do not have availability to work on this week as my efforts are focused on the reset button and issue 1533
4. ETA: Need to determine this testings' priority level in order to know ETA
5. Pictures or links* (if necessary): N/A

**Comment by ExperimentsInHonesty** [comment]
Needs to be prioritized and put in the prioritized backlog

**Comment by abbyrivard** [comment]
Issue Update:
This research is a priority _after_ the My Projects Page Usability Testing. Once the My Projects Page Research Plan is complete, a UXR can create the research plan and begin this issue with the knowledge that as soon as the My Projects Page is ready (dev issues completed) for research, this issue might need to be put on ice until the My Projects Page Usability Testing has been completed.

**Comment by abbyrivard** [comment]
The My Projects Page research plan and question creation has been completed, however all the features of the My Projects Page have been implemented by dev yet. Because of this, we are pivoting the research teams focus to this issue until the research for #1663 is able to continue.

**Comment by ExperimentsInHonesty** [comment]
@melissaperry09 Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):
