### ISSUE TITLE
Research EPIC: FAQ Page Usability Testing (Users: Dogfooding)

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1665]
### Dependency
- #1344
- #1714 
- #2073 

### Overview
We need to conduct a general usability testing on the "FAQ" page for end users and identify any pain points with the current designs and functions of this page. This page has not been through any testing thus far and therefore requires a general user test. 

#### Detail 
We're not testing:
- if a user needs help on something in the My Projects Page, do they know where to find it?
- if a user does know where to find the content/answers (to their questions in the FAQ page), do the answers explain the information adequately - does the user understand it?

### Action Items
- [x] #2100
- [ ]  #1690
   - [ ] Get Research Plan approved by PMs
- [ ] #1707
- [ ] #2449 
   - [ ] Run proposed User Testing questions by PMs
- [ ] #1708
   - [ ] Conduct UXR Team Training
   - [ ] Recruit Interviewees 
   - [ ] Schedule Interviews
   - [ ] Conduct Interviews
- [ ] #2101
   - [ ] FigJam Board 
- [ ] #2102
   - [ ] Create Presentation of findings for Stakeholders
- [ ] #1821

### Resources/Instructions
- [RP008 Research Overview](https://github.com/hackforla/tdm-calculator/wiki/RP008:-FAQ-Page-Usability-Testing)
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1m4l2BKm_nKL1nUQFPl1pME01w4Kk7esNVu-GiJQyjAE/edit?gid=0#gid=0)
- [2025-04-15 Release Deck, Slide 1665](https://docs.google.com/presentation/d/1_Xszms-WP5drcEXG3E_d8EiJ7qqtgqehZ1-Hw6p1xCw/edit#slide=id.g34cb9a1a267_0_385)

**Comment by ExperimentsInHonesty** [comment]
moved to new issue approval because dependencies are resolved.

**Comment by abbyrivard** [comment]
@abbyrivard 
Dependent on epic 2427 being closed - need a new rp for answering the questions:
- if a user needs help on something in the My Projects Page, do they know where to find it?
- if a user does know where to find the content/answers (to their questions in the FAQ page), do the answers explain the information adequately - does the user understand it?
