### ISSUE TITLE
EPIC: Design Mock up instructions page for FAQ page 

### ISSUE THREAD

**Issue by marlenamellody** [hackforla/tdm-calculator#1686]
### Dependency
- [ ] #1726 
- [x] #1731 
### Overview
We need to draft instructions for how to manage the content on the FAQ page for Admins, so that after the handover LADOT and LACP will know how to do it

### Details
- On the dev site (not yet on prod?), there is an edit button on the FAQ page, when you are logged in as admin <img src="https://github.com/hackforla/tdm-calculator/assets/37763229/5d3fd83a-dd55-4460-bd8e-a10cfc040f0e" width=140px>
- once clicked you can perform actions <BR><img src="https://github.com/hackforla/tdm-calculator/assets/37763229/9efd51a6-6a33-436b-95ab-f246dab5e826" width=400px>

### Action Items
- [ ] Write up instructions for each of the actions
  
     - [x] add new category
     - [x] add new FAQ Question and Answer
     - [x] edit Question
     - [x] edit Answer
     - [x] Change the order of categories or questions
  
     - [x] Delete Question and Answer
     - [x] Delete Category
     - [x] add link into an answer
- [ ] Review with Product and Research so that they can give feedback for changes
- [ ] Get Stakeholder sign-off via the stakeholder meeting slidedeck
- [ ] Close child issues
  - [x] #1731 
  - [ ] #1726
- [ ] turn into webpage mockup

### Resources/Instructions
- https://tdm-dev.azurewebsites.net/
- https://github.com/hackforla/tdm-calculator/issues/1666

**Comment by yiranshan** [comment]
size added on for this issue, @Parisajf please adjust "feature", " milestone", " priority" tags.

**Comment by lbeatonn** [comment]
UPDATE: We are waiting on more information from Bonnie on where these questions live on the site and whether there are more questions to be added to these tutorials

**Comment by lbeatonn** [comment]
UPDATE NOTES (more actions needed): FAQ Instruction will be accessible via a menu off of the main bar. We don't know what to call the link. Link will be for admin to be able to view the FAQ Instructions. There needs to be an edit link with the ability to edit the Instruction Page.
    - **Redesign this to look exactly like the FAQ (with categories)** and keep the search feature

**Comment by malubongestab** [comment]
Hi @thetanmancan, I believe this issue also can be closed.

What is asked here (all Action Items) was already addressed in issue #1731 and @lbeatonn updates comments are already being addressed and worked on in issue #1726 where I created the Admin Guide page mimicking the FAQ page, as requested.

To be honest I do not understand the necessity of two issues that request the same work. The information was sort of scattered and this is what made it so confusing for me to understand what was requested when I was assigned to issue #1726. 

So in my opinion this issue can also be closed.

**Comment by thetanmancan** [comment]
@malubongestab: I agree. As far as I can tell, #1731 was designed to cover the content of certain questions, and #1726 covers everything else. And since you're now covering everything related to this Admin Guide under #1726, I don't see any good reason to keep #1686 or #1731 open anymore. I'm closing this issue accordingly.
