### ISSUE TITLE
Create Research Plan for FAQ Page Usability Testing

### ISSUE THREAD

**Issue by abbyrivard** [hackforla/tdm-calculator#1690]
### Dependency
- #1663
- #2100 
- Associated Issue, not a true dependency 
   - #2379

### Overview
We need to create a research plan to define the research scope, goals, and methods for the FAQ page Usability Testing. 

### Action Items
- [x] Create Research Plan Google Doc utilizing the TDM style guides 
- [x] Add information for each section below and check off as you go:
    - [x] Background
    - [x] Research Questions and Objectives
    - [x] Participants
    - [x] Research Assumptions
    - [x] Research Methods
    - [x] Data Analysis
    - [x] Timeline
    - [x] Resources
        - [x] Wiki Pages
        - [x] Further Documentation
- [x] Add research plan to issue #2353 
- [x] Get Research Plan approved by PMs
- [x] Check off the Dependency on #1707 
- [x] Add Research Plan Link to resources section of #1821  
- [x] Add Research Plan to the wiki documentation

#### Resources for creating this issue
- #1665 
- Reference previous research plan: [TDM: RP004 Reset Button Research Plan](https://docs.google.com/document/d/12GB3YQfh6cy9ynXriRNNwWAMQ8PTpkHfc8J4qPBXMO0/edit).
- Wiki [FAQs page Usability Testing](https://github.com/hackforla/tdm-calculator/wiki/RP008-FAQ-Page-Usability-Testing)

#### Resources gathered during the completion of this issue
- [RP008 Research Plan](https://docs.google.com/document/d/1cVCFmFgS3Wa-_f33WOTq2bGNbFZCIaz2izRufS2m21k/edit?tab=t.0)
- [2025-04-15 Release Deck, slide 1690](https://docs.google.com/presentation/d/1_Xszms-WP5drcEXG3E_d8EiJ7qqtgqehZ1-Hw6p1xCw/edit#slide=id.g34cb9a1a267_0_252)
- [Spreadsheet RP008: FAQs By Relevancy to User Testing](https://docs.google.com/spreadsheets/d/1m4l2BKm_nKL1nUQFPl1pME01w4Kk7esNVu-GiJQyjAE/edit?gid=0#gid=0)

**Comment by ExperimentsInHonesty** [comment]
@xxl228 Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by melissaperry09** [comment]
This research plan is complete, and has been added to the resources gathered section of this issue along with #2353 for review with product.

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard @melissaperry09 I moved this issue out of the icebox and to new issue approval because the dependencies are cleared.   Please add a ready for prioritization label to this issue when its ready.

**Comment by abbyrivard** [comment]
@ExperimentsInHonesty I added the new epic FAQ issue #2379 as the new dependency for this issue and put it back into the icebox, unless you feel like we can continue on without issue 2379 being completed.

**Comment by abbyrivard** [comment]
@ExperimentsInHonesty Update: I've updated the research plan based on the notes you left. Also created an additional task that will be assigned out to research this week - issue #2434 as a conclusion to one of the blockers on the research plan being that some questions were out of scope.

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard I left you the following comment in the document

>Does the layout and content support registered and unregistered users who might navigate to the page for locating specific information? 

How would you test this?  Meaning, are you going to start the usability test by having them look for something specific and have them self identify that the FAQ is where they would find that?  If so, I would change this wording to include the part in brackets below:

Does the [title,] layout and content support registered and unregistered users who might [need to] navigate to the page for locating specific information?

**Comment by abbyrivard** [comment]
Conclusion addressed in issue #2353 resulting in the suggested formatting being adopted. 
Conclusionary comment:
"RP008 approved, need to make new issue though - see below instructions also listed on https://github.com/hackforla/tdm-calculator/issues/1665
Dependent on epic 2427 being closed - need a new rp for answering the questions:

if a user needs help on something in the My Projects Page, do they know where to find it?
if a user does know where to find the content/answers (to their questions in the FAQ page), do the answers explain the information adequately - does the user understand it?

UPDATE: New Epic created: https://github.com/hackforla/tdm-calculator/issues/2444"

> [@abbyrivard](https://github.com/abbyrivard) I left you the following comment in the document
> 
> > Does the layout and content support registered and unregistered users who might navigate to the page for locating specific information?
> 
> How would you test this? Meaning, are you going to start the usability test by having them look for something specific and have them self identify that the FAQ is where they would find that? If so, I would change this wording to include the part in brackets below:
> 
> Does the [title,] layout and content support registered and unregistered users who might [need to] navigate to the page for locating specific information?
