### ISSUE TITLE
EPIC: Change React Framework

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#1706]
### Overview
Create React App is the framework used originally to create the TDM project. It is now deprecated and no longer supported, so the recommended action is to switch to a more current, maintained framework.  The current most popular frameworks for React are Next.js and Vite, so those are the best candidates.  This is a BIG project - particularly if we choose Next.js

### Action Items
- [x] Evaluate Next.js and Vite as possible replacements.
- [x] This will probably involve creating a new repo from scratch, and migrating React components piecemeal into the new repo.
- [x] Both Next.js and Vite highly recommend using Tailwind for CSS styling, which will involve a major re-work of our style implementation.  This is a big project as well, but may allow us to better implement a design system.
- [ ] I haven't fully investigated Next.js yet, but it's server-side implementation MIGHT allow us to integrate Okta authentication, since it acts somewhat like a conventional web site.
- [ ] Next.js might also allow us to move all of our web api server implementation into the server-side part of the React Application ???
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the [staging deck on this slide](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g316ffcc5f71_4_0) 
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources/Instructions
https://nextjs.org/
https://vitejs.dev/

**Comment by Parisajf** [comment]
John said we are still working on the first check mark.

**Comment by entrotech** [comment]
Re-wrote the description per our experience with Vite on the Food Oasis project.

**Comment by Vihardesai20** [comment]
@entrotech any update on this ? 
Estimated ETA was 2025-03-06 for this issue on staging deck

**Comment by ExperimentsInHonesty** [comment]
new guestimate is Estimated ETA: 2025-04-30 (4 weeks from 2025-04-01)
