### ISSUE TITLE
Research EPIC: FAQ Instructions and Features Usability Testing Stage 1 (Users: Dogfooding)

### ISSUE THREAD

**Issue by Parisajf** [hackforla/tdm-calculator#1722]
### Dependency
- #1686 
- #2592

### Overview
We need to test the instructions for how to use the FAQ editing so that we can release the instructions to dev.

### Action Items
- [x] #2104
- [x] #2105
   - [ ] Get Research Plan approved by PMs
- [ ] #2106
- [ ] #2450 
   - [ ] Run proposed User Testing questions by PMs
- [ ] #2107
   - [ ] Conduct UXR Team Training
   - [ ] Recruit Interviewees
   - [ ] Schedule Interviews
   - [ ] Conduct Interviews
- [ ] #2108
- [ ] #2109
- [ ] #2110
- [ ] create stage 2 to be done with users: LADOT and LACP

### Resources/Instructions
- [FAQ Page](https://tdm-dev.azurewebsites.net/faqs)
- Instruction will be uploaded on the #1686

**Comment by Parisajf** [comment]
@1x1rohaun Any updates Robert?

**Comment by ExperimentsInHonesty** [comment]
Moved this to new issue approval because the dependencies are closed

**Comment by JackHaeg** [comment]
Moving this issue to new issue approval because dependency has been satisfied. If this issue still has other dependencies and should remain in the icebox, please add this dependency & change the status back to "icebox."
