### ISSUE TITLE
Site Audit: Check Create Project page 2 for visual design consistency

### ISSUE THREAD

**Issue by NilakshiS** [hackforla/tdm-calculator#1955]
### Dependencies
- #1901
 
### Overview
Check the Create Project page 2 for consistency with the design system and document any discrepancies.

#### Details
We will find major and minor items.  Don't skip anything, no matter how small.  After the issues are made to fix, we will put them in the prioritized backlog and low priority items might not get finished but will be documented for the stakeholders.

### Action Items
Document the value of these properties for each of the following elements present on page. If an element on the list is not on the page, mark it as N/A or ~~strikethrough~~ the item. 

Note: The list of elements is not exhaustive, some pages might have more elements and some elements might get repeated while checking for other values.

- [x] Color 
  <details><summary>List of Elements</summary>
    
     - [x] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Typography
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Shadows
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Sizes 
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Spacing
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Border
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Border Radius
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 
- [x] Icons & Images
  <details><summary>List of Elements</summary>
    
     - [ ] Heading and Paragraph Texts
     - [ ] Buttons
     - [ ] Input and Fields
     - [ ] Accordions
     - [ ] Tooltips
     - [ ] Infoboxes
     - [ ] Links
     - [ ] Any Remaining Page/Content Text or Backgrounds
  </details> 

- [ ] bring the comments from Figma to this issue and combine with prior analysis detailed in the comment above https://github.com/hackforla/tdm-calculator/issues/1955#issuecomment-2652786281
- [ ] If issue https://github.com/hackforla/tdm-calculator/issues/2013 is completed before your work on this issue is complete, please incorporate any changes from https://github.com/hackforla/tdm-calculator/issues/2013 into this audit.
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] review with Lead Designer and document which issues will be made into bug issues and design issues.
- [ ] write issues

### Resources/Instructions

- What to check:
  - **Color:** Check for adherence to palette and correct usage (for e.g.: incorrectly using "Red" color for a positive action on a button).
  - **Typography:** Check for correct size and other font attributes, correct usage (for e.g.: incorrectly using Header 4 style on paragraph text).
  - **Shadows:** Check for correct blur, spread, color and opacity, correct usage (for e.g.: elements that don't need drop shadow but have them).
  - **Sizes:** The current style guide does specify any size guidelines except for buttons, make sure the buttons follow the size guidelines and for the rest of the components just note down the width and height.
  - **Spacing:** The current style guide does specify any spacing guidelines except for buttons, make sure the buttons follow the spacing guidelines and for the rest of the components just note down the margins and padding.
  - **Border:** Check for correct stroke width, color and other attributes, correct usage (for e.g.: buttons that shouldn't use borders but have them).
  - **Border Radius:** Check for correct radius amount and sides it's applied to, correct usage.
  - **Icons and Images**: Check for correct icons & images being used in recommended color and sizes.

- [Template for site audit on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4472-16921&node-type=canvas&t=NguUgNljY5ekKthK-0)
- [TDM Calculator dev site Login page](https://tdm-dev.azurewebsites.net/login)
- [Style Guide Presentation](https://docs.google.com/presentation/d/1I4q35NL2WW2RpksIyawhHCd8qJnrjme1ZDNIBxu24hQ/edit#slide=id.g2a6d1bfeb46_0_103)
- [Design System on Figma](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=0-1&t=W6TPfPgXZGyIfTkR-1)
- [Annotated Figma file from previous site audit](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=8710%3A19764&t=eNG5rGUzIyucDpRs-1)
- This video might be helpful: [Freeze screen & inspect disappearing elements](https://developer.chrome.com/blog/devtools-tips-35). I used the "timeout with snippets" method from this video recently.
- [Figma page for this issue](https://www.figma.com/design/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4919-17242&t=LzTRtH92dNx7JXjn-1)

#### Slides
- not for stakeholder

**Comment by greenishviolet** [comment]
### 12/17 Progress Update

#### Progress
I took relevant screenshots and am currently auditing colors used in Create Project Page 2.

#### Blockers
I am having trouble finding color values of elements that only appear on hover and transparent. I am researching how to do that using Chrome DevTools.

#### Availability
I have around 10 hours to contribute this week.

#### ETA
I can finish this in one or two weeks.

#### Pictures
<details>
<summary>Screenshots of Create Project Page 2</summary>

![Image](https://github.com/user-attachments/assets/1f3d15a4-b10a-4c84-8bc6-3958c40f205e)

</details>

<details>
<summary>In Progress Color Audit</summary>

![Image](https://github.com/user-attachments/assets/1e6185d0-d98f-49f9-b854-98303f541dee)

</details>

**Comment by NilakshiS** [comment]
@greenishviolet This video might be helpful: [Freeze screen & inspect disappearing elements](https://developer.chrome.com/blog/devtools-tips-35). I used the "timeout with snippets" method from this video recently. Let me know if you need help!

**Comment by greenishviolet** [comment]
@NilakshiS Thanks! I'll check it out!

**Comment by thetanmancan** [comment]
Hi @greenishviolet. If issue #2013 is completed before your work on this issue is complete, please incorporate any changes from #2013 into this audit. Thank you.

**Comment by thetanmancan** [comment]
Hey @greenishviolet. I hope you had a nice winter vacation. Since we're back in action as of this week, please provide an update for this issue using the following format by Tuesday night. Thank you!

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by greenishviolet** [comment]
### 01/07 Update

#### Progress
- I am currently focusing on audits that would be finished quicker
- I had to redo some audits because I didn't take in-line tooltips (no longer in design system) into consideration

##### Audit Status
- **Completed:** Shadows, Border Radius
- **In-Progress:** Icons & Images
- **Paused:** Color (may need to redo)
 - **Not Started:** Typography, Sizes, Spacing, Border

#### Blockers
- As mentioned last week, progress on this issue is slow because I am trying to figure out how to use DevTools.

#### Availability
I have around 8 to 10 hours to work on this issue this week

#### ETA
I might need 1 or 2 more weeks on this issue.

#### Pictures
<details>
<summary>Completed Audit of Shadows</summary>

![image](https://github.com/user-attachments/assets/17ef1679-b151-46de-966d-e8e249e53d52)

</details>

<details>
<summary>Completed Audit of Border Radius</summary>

![image](https://github.com/user-attachments/assets/335a72c8-6d93-452a-a13f-02b8a65b3d64)

</details>

<details>
<summary>In Progress Audit of Images and Icons</summary>

![image](https://github.com/user-attachments/assets/a130c03c-3eb5-4470-878c-3d7b187918b8)

</details>
<details>
<summary>Paused Color Audit</summary>

![Image](https://github.com/user-attachments/assets/1e6185d0-d98f-49f9-b854-98303f541dee)

</details>

**Comment by greenishviolet** [comment]
### 01/14 Update

#### Progress
- **Completed:** Shadows, Border Radius, Icons & Images
- **In-Progress:** Borders
- **Next up:** Typography, Spacing, Sizes, Color

#### Blockers
- Figuring out how to use Chrome Inspect and understanding CSS terminology
- Finding Position and Dash by values in Chrome Inspect

#### Availability
I've been busy this week, so I don't have much time to work on this issue. I can dedicate around 4 hours.

#### ETA
At this point, I'm not sure when I will finish this issue. I'm hoping I can finish in 2 weeks.

#### Pictures
<details>
<summary>Completed Audit of Shadows</summary>

![image](https://github.com/user-attachments/assets/17ef1679-b151-46de-966d-e8e249e53d52)

</details>

<details>
<summary>Completed Audit of Border Radius</summary>

![image](https://github.com/user-attachments/assets/335a72c8-6d93-452a-a13f-02b8a65b3d64)

</details>

<details>
<summary>Completed Audit of Images and Icons</summary>

![Image](https://github.com/user-attachments/assets/1ff07387-7d4a-475c-8de0-2b63f19b92c2)

</details>
<details>
<summary>In Progress Audit of Border</summary>

![Image](https://github.com/user-attachments/assets/a9f91a36-c93e-4a49-b7b1-adb1f068ba2d)

</details>

**Comment by greenishviolet** [comment]
### 01/21 Update

#### Progress
- **Completed:** Typography, Shadows, Border Radius, Icons & Images, Borders
- **In-Progress:** Sizes
- **Next up:** Spacing, Color

#### In Progress Summary of Audit
I'm noticing that a lot of the misuse of UI elements (e.g. color, shadows, icons, etc.) arises from the fact that older, deprecated components are being used, like the Inapplicable Strategies Modal (Information Modal) and In-line Text Tooltips (to be replaced with Popovers). I also noticed that the button group (Nav buttons and disabled primary button) in the bottom does not match the button styling in the design system.

#### Blockers
- Figuring out how to use Chrome Inspect and understanding CSS terminology
- I wasn't able to find the Position and Dash by values in Chrome Inspect for the Border Audit

#### Availability
I've been busy this week, so I don't have much time to work on this issue. I can dedicate around 4 hours.

#### ETA
At this point, I don't know when I will finish this issue. I hope to finish in 2 weeks. I plan to complete the audit and do one more review to ensure I got everything down.

#### Pictures
<details>
<summary>Completed Audit of Shadows</summary>

![image](https://github.com/user-attachments/assets/17ef1679-b151-46de-966d-e8e249e53d52)

</details>

<details>
<summary>Completed Audit of Border Radius</summary>

![Image](https://github.com/user-attachments/assets/a5719698-a742-406f-9673-7013532c77da)

</details>

<details>
<summary>Updated Audit of Images and Icons</summary>

![Image](https://github.com/user-attachments/assets/80957723-ed29-4a8b-81f5-9917ecbb17bb)

</details>

<details>
<summary>Completed Audit of Border</summary>

![Image](https://github.com/user-attachments/assets/6ca063e8-d3fb-4c07-a62d-5c5f2b3f9ad9)

</details>

<details>
<summary>Completed Audit of Typography</summary>

![Image](https://github.com/user-attachments/assets/62729aa3-4b66-4ae4-b4b9-e9442d32db7a)

</details>

**Comment by greenishviolet** [comment]
### 01/28 Update

#### Progress
I was not able to work on this issue this weekend. I will work on this issue on Wednesday.

#### Blockers
Finding the time to work on this issue.

#### Availability
I can dedicate around 4 hours

#### ETA
Possibly 2 weeks?

#### Pictures
N/A

**Comment by greenishviolet** [comment]
### 02/04 Update

#### Progress
- **Completed:** Typography, Shadows, Border Radius, Icons & Images, Borders, Sizes, Spacing
- **Next up:** Color

#### Blockers
- Figuring out how to use Chrome Inspect and understanding CSS terminology

#### Availability
I've been busy this week, so I don't have much time to work on this issue. I can dedicate around 4 hours.

#### ETA
I can probably finish up by next week.

#### Pictures
<details>
<summary>Completed Audit of Shadows</summary>

![image](https://github.com/user-attachments/assets/17ef1679-b151-46de-966d-e8e249e53d52)

</details>

<details>
<summary>Completed Audit of Border Radius</summary>

![Image](https://github.com/user-attachments/assets/a5719698-a742-406f-9673-7013532c77da)

</details>

<details>
<summary>Completed Audit of Images and Icons</summary>

![Image](https://github.com/user-attachments/assets/80957723-ed29-4a8b-81f5-9917ecbb17bb)

</details>

<details>
<summary>Completed Audit of Border</summary>

![Image](https://github.com/user-attachments/assets/6ca063e8-d3fb-4c07-a62d-5c5f2b3f9ad9)

</details>

<details>
<summary>Completed Audit of Typography</summary>

![Image](https://github.com/user-attachments/assets/62729aa3-4b66-4ae4-b4b9-e9442d32db7a)

</details>

<details>
<summary>Completed Audit of Sizes</summary>

![Image](https://github.com/user-attachments/assets/5e15eb0b-385b-4ba2-8517-45f0925e52a9)

</details>

<details>
<summary>Completed Audit of Spacing</summary>

![Image](https://github.com/user-attachments/assets/917ac93f-b248-4c51-b76c-ead422795057)

</details>

**Comment by greenishviolet** [comment]
# 02/04 Update

## Progress
I noticed the new popover components were implemented, so I updated previous audits to include those. As of now, I have completed all audits.

### Findings
This evaluation excludes discussion of size, spacing, and border-radius, as the design system has not yet established formal guidelines for these elements.

####  Issues with Buttons (Important)
1. **Text Buttons** - Currently, spacing and type styles in the text buttons on the dev site do not match what is in the design system.
2. **Inconsistencies in Button Styles** - It seems that the updated button styles in our design system have yet to be implemented on the Dev site. Due to this, there were inconsistencies in sizes, color, spacing, shadows, etc.
3. **Issues with disabled buttons** - The Save Project button is disabled in Create Project Page 2, but it uses the same color for default buttons. This can create confusion for users, who may try to save their work while they are on this page. <br>
     Furthermore, there are issues with color contrast with the Save Project button in the Dev site. The color contrast ratio is 1.86, which does not meet AA or AAA compliance levels in WCAG. Likewise, disabled buttons in our design system also has the same color contrast issues. Disabled primary buttons have a color contrast ratio of 2.85. To meet AA and AAA compliance levels, the color contrast ratio should be 4.5:1 and 7:1, respectively.

#### Consistency in Text Styles and Colors
1. Paragraph text styles are inconsistent on Page 2 of Create Project. Despite using 16px Calibri extensively on the Create Project page, the line heights and letter spacings are inconsistent and conflict with the already established Paragraph Style in our design system. <br>
     Instances of Inconsistencies in Paragraph Style Usage:
     - **Form labels, error messages, & units** - line-height: 16px / letter-spacing: 0%
     - **Popover text** - line-height: 19.2px / letter-spacing: 0%
     - **Text Input** - line-height: Normal / letter-spacing: 0%

2. Text color is either Grayscale / Black (#000000) or Secondary Colors / Dark Navy (#0F2940). For some, this difference is subtle and unnoticeable. Because dark navy is used so much more, the black text elements (and to a certain extent icons) feel visually disjointed. <br>
     **Grayscale / Black usage in elements:** Page heading, text buttons, text input, arrow icons in navigation buttons, button labels

#### Implementing New Components (Popovers and Information Modals)
Most of the inconsistencies in the color, type styles, icon usage, etc. arose from the fact that defunct components (In-line Text Tooltip and modal) were being used. Dev issues to replace these components have been open to address this (#1986 and #1997).

Currently, Issue #1997 has been completed, and new popover components have been implemented. However, I did notice the following discrepancies:
- **Spacing:** The internal spacing does not match the component in the design system. The popovers in the Dev site have a padding of 16px all-around, and the close button is absolutely positioned in the top right corner. This may be a problem when the edit icon is added at the bottom right to give admin users the ability to edit tooltips (Issue #1903). Furthermore, there should be 12px between paragraphs.

<details>
<summary>Popover Internal Spacing</summary>

![Image](https://github.com/user-attachments/assets/02431e28-3a66-4596-8b70-3065c899fad0)

</details>

- **Border & Close Icon Color:** The border color is #939393 on the dev site, but Grayscale / Gray is #939393 with #000000 (20% opacity) layered on top of it twice. The closest color to that is #5E5E5E.

<details>
<summary>Grayscale/Gray</summary>

<img width="326" alt="Image" src="https://github.com/user-attachments/assets/35e8e955-9e4a-480d-b2b3-029a80ea5296" />

</details>

#### Drop Shadows
<details>
<summary>Drop Shadows</summary>

![Image](https://github.com/user-attachments/assets/eb9059e0-6d3a-4f05-8127-cb856d265669)

</details>

In Issue #1743, Nami and I have created drop shadow styles, which the new modal components and popover components use. Buttons in the dev website do not use these shadow styles. This is because the components with drop shadows have not been updated with these styles yet (such as buttons, info boxes, etc.).


## Blockers
I do not have any blockers, just questions about the next steps.

@thetanmancan, I'm a little bit confused about what to do next for this issue since the task wasn't to design something. After reading this progress update, could you let me know what the next steps should be (preferably on Slack)?

## Availability
I can dedicate around 4 to 5 hours to this issue.

## ETA
I think I am done with this issue for now.

## Pictures
<details>
<summary>Updated Shadows Audit</summary>

![Image](https://github.com/user-attachments/assets/8991a096-4ca6-4d44-aa16-5bd9ad28cfd6)

</details>

<details>
<summary>Updated Border Radius Audit</summary>

![Image](https://github.com/user-attachments/assets/6fb00a27-6877-40ec-b17d-80f2c6d10978)

</details>

<details>
<summary>Updated Images and Icons Audit</summary>

![Image](https://github.com/user-attachments/assets/9508f7b0-2d0d-4134-80c0-971d6ab2c803)

</details>

<details>
<summary>Updated Border Audit</summary>

![Image](https://github.com/user-attachments/assets/485adf1f-2064-4f78-b52d-dc93aad82c1c)

</details>

<details>
<summary>Updated Typography Audit</summary>

![Image](https://github.com/user-attachments/assets/fffbe818-4b31-42b3-9f71-e41fd1463bfd)

</details>

<details>
<summary>Updated Sizes Audit</summary>

![Image](https://github.com/user-attachments/assets/6036c8d9-ebf7-4724-99aa-8d5a20790e28)

</details>

<details>
<summary>Updated Spacing Audit</summary>

![Image](https://github.com/user-attachments/assets/802e8dfb-ea2b-48fb-964e-3dd5a43b9af4)

</details>

<details>
<summary>Completed Color Audit</summary>

![Image](https://github.com/user-attachments/assets/f3e0d6a5-1867-4f3a-9c29-81602b8596db)

</details>

**Comment by greenishviolet** [comment]
@thetanmancan - Personally, I think focusing on fixing the major issues would be more effective because those revisions would also fix a majority of the minor fixes. Some of these issues are big usability and accessibility issues that are important, such as the disabled buttons.

**Comment by thetanmancan** [comment]
Hi @greenishviolet. I've moved this issue back to In Progress. Once you've finished #2004, please come back and write up an exhaustive list of changes that need to be made as a result of your findings from this issue, whether they be bugs or changes we need to make to our design system. Please let me know if you have any questions. Thank you.

**Comment by ExperimentsInHonesty** [comment]
- @thetanmancan @greenishviolet If this can't be worked on until the issues are resolved on #2004, then this needs to go into the icebox with the blocker defined.

**Comment by ExperimentsInHonesty** [comment]
The remaining task items for this issue are
- [ ] bring the comments from Figma to this issue and combine with prior analysis detailed in the comment above https://github.com/hackforla/tdm-calculator/issues/1955#issuecomment-2652786281
- [ ] review the findings with Lead Designer and document which issues will be made into bug issues and design issues.
- [ ] write issues

**Comment by ExperimentsInHonesty** [comment]
@greenishviolet I have updated the action items at the top of the issue, and updated the details with decision made on level of detail.  Please hide any comments that are no longer relevant (if they have been replaced by newer comments that are inclusive of all the screenshots needed).

**Comment by greenishviolet** [comment]
### 3/11 Progress
I did not work on this issue.

#### ETA
I'm not sure when this issue will be completed. Possibly, 1 to 2 weeks after I finish #2004?

**Comment by greenishviolet** [comment]
### 3/18 Progress
I did not work on this issue.

#### ETA
I'm not sure when this issue will be completed. Possibly, 2 to 3 weeks after I finish #2004?

**Comment by thetanmancan** [comment]
@greenishviolet, I've removed you as the assignee and put this issue back into the Prioritized Backlog until someone (hopefully you) can get around to writing up all the issues you discovered. Please let me know if you have any questions or concerns about this. Thank you.

**Comment by Rabia2219** [comment]
> [!NOTE]
> NOT in staging deck as of 2025-05-06...please review...

**Comment by JaimeCucalon** [comment]
Last comment on Issue #2370 makes note of Gray inconsistencies. 
The #5E5E5E color is used for the button's text disabled state.
