### ISSUE TITLE
Update all issues to have instructions for updating the staging deck

### ISSUE THREAD

**Issue by jmeasow** [hackforla/tdm-calculator#1963]
### Overview
We need to have instructions for updating the staging deck on every issue, so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.

### Action Items
- Create the following issues
   - [x] #1968
   - [x] #1970
   - [x] #1971
   - [x] #1972
   - [x] #1973
- [x] Add the appropriate labels (see 1968), including ready for prioritization
- [x] Add the milestone 03 - Project Manangement
- [x] Update all templates
- [ ] Check all issues have the new template

#### Sections
- Discussion Topics (product or research)
- Design Review (design)
- Updates to Review & Release (dev)

#### Template
````
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.

### Action Items

- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Add the text from template to each
- [ ] Check to see if there is a slide in the Staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Resources
- [Project Board, Prioritized Backlog](https://github.com/orgs/hackforla/projects/68/views/1?filterQuery=status%3A%22Prioritized+Backlog%22)
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
- This issue is part of an epic https://github.com/hackforla/tdm-calculator/issues/1963

#### Sections
- Discussion Topics (product or research)
- Design Review (design)
- Updates to Review & Release (dev)

### Template
```
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the slide in the staging deck
- [ ] Get Stakeholder sign-off via the stakeholder meeting slide deck.

### Resources

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide ISSUE NUMBER]
- Release Deck
   - [YYYY-MM-DD Release Deck, slide ISSUE NUMBER]
```
````

**Comment by senakim18** [comment]
I'll check all issues added to staging deck and close all the epics attached to this issue.

**Comment by ExperimentsInHonesty** [comment]
New action items
- [ ] Identify all the issues from the [issues tab](https://github.com/hackforla/tdm-calculator/issues), that are not in the deck making a list in a comment on this issue
- [ ]

**Comment by ExperimentsInHonesty** [comment]
### Issues in not in the deck

**Comment by senakim18** [comment]
All Open Issues not in the deck as of 2025-03-09. 

19, 413, 475, 498, 687, 724, 765, 866, 888, 890, 936, 955, 975, 1048, 1051, 1075, 1107, 1125, 1160, 1191, 1311, 1312, 1315, 1327, 1333, 1341, 1357, 1360, 1364, 1366, 1396, 1470, 1502, 1503, 1531, 1533, 1567, 1593, 1617, 1618, 1619, 1652, 1656, 1662, 1664, 1665, 1666, 1690, 1694, 1707, 1708, 1717, 1722, 1724, 1744, 1754, 1755, 1780, 1792, 1793, 1795, 1821, 1861, 1862, 1863, 1865, 1866, 1867, 1886, 1897, 1918, 1938, 1963, 1967, 1969, 1992, 2001, 2002, 2006, 2007, 2024, 2025, 2026, 2027, 2045, 2050, 2053, 2071, 2081, 2084, 2085, 2086, 2087, 2088, 2090, 2093, 2094, 2096, 2097, 2100, 2101, 2102, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2017, 2124, 2129, 2130, 2135, 2140, 2142, 2149, 2150, 2151, 2152, 2153, 2154, 2156, 2158, 2161, 2162, 2163, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175

**Comment by ExperimentsInHonesty** [comment]
@senakim18 
>Q: All Open Issues not in the deck as of 2025-03-09. I made a [Staging: Issues Check, Filter: Issues not accounted for](https://docs.google.com/spreadsheets/d/1R_f0nVDKrX73JrJeKzc_GHJuftNNRU6PHDHnMZXjDdU/edit?gid=487934054#gid=487934054&fvid=903221456) to help with tracking. Should this go in the TDM Google Drive?

A: Yes, I moved it and the staging deck to the folder that is [not shared with stakeholders](https://drive.google.com/drive/folders/1PMM__yb4bhk_TS8L7nSSdfCTjOBL2DqG)

**Comment by ExperimentsInHonesty** [comment]
@senakim18 When we have this slide on the staging deck, we should have it be an EPIC progress slide and there should be other Epic progress slides as well.  Let's discuss more.
- https://github.com/hackforla/tdm-calculator/issues/1652

**Comment by ExperimentsInHonesty** [comment]
@senakim18 Please provide update or let me know if you need to be removed from the issue

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by senakim18** [comment]
> [@senakim18](https://github.com/senakim18) When we have this slide on the staging deck, we should have it be an EPIC progress slide and there should be other Epic progress slides as well. Let's discuss more.
> 
> * [Epic: Implement Submission Features #1652](https://github.com/hackforla/tdm-calculator/issues/1652)
> 
> ### Epics to track
> 
> * Documentation Epic: [EPIC: Helpfile Guidelines/Instructions Usability Testing #1666](https://github.com/hackforla/tdm-calculator/issues/1666)
> 
> ### Issues for Research Epics slide
> 
> [Issues Tab, label:"role: ui/ux research" label:epic ](https://github.com/hackforla/tdm-calculator/issues?q=state%3Aopen%20label%3A%22role%3A%20ui%2Fux%20research%22%20label%3Aepic)

@ExperimentsInHonesty This issue has the "not for stakeholder" label and listed on the last slide in the staging deck. Should this not be the case and a slide created for it? I checked the slide for #1666 and left you a comment asking how you'd like the slide to be organized.

**Comment by lola3736** [comment]
@senakim18 @ExperimentsInHonesty 
Has the above query been addressed?  

Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary):

**Comment by lola3736** [comment]
Per slack communication, @senakim18 confirmed she is unavailable for the next 2weeks, hence issue is moved to Prioritized Backlog needs to be re-assigned.

**Comment by ExperimentsInHonesty** [comment]
Clean up the templates and then prioritize so that all issues that are open get the correct template

**Comment by ExperimentsInHonesty** [comment]
```
#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide ISSUE NUMBER]
- Release Deck
   - [YYYY-MM-DD Release Deck, slide ISSUE NUMBER]
```

**Comment by ExperimentsInHonesty** [comment]
[Issues without the X1 label](https://github.com/hackforla/tdm-calculator/issues?q=is%3Aopen+-label%3A%22X1+-+slide+fixd%22+)

### Label
[X1 - slide fixd](https://github.com/hackforla/tdm-calculator/labels/X1%20-%20slide%20fixd)

**Comment by Rabia2219** [comment]
#### Need Bonnie's Review

- https://github.com/hackforla/tdm-calculator/issues/2027#issuecomment-2847931639

**Comment by ExperimentsInHonesty** [comment]
- [ ] https://github.com/hackforla/tdm-calculator/issues/2414

**Comment by ExperimentsInHonesty** [comment]
- [ ] https://github.com/hackforla/tdm-calculator/issues/2084
- [ ] https://github.com/hackforla/tdm-calculator/issues/2182
