### ISSUE TITLE
Epic: Website Spelling Checks and Structure

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#413]
### Dependency 
- #1146
- #2206 
- #2404 
- #2492 

### Overview
We need to spell check the website, both manual and automated, before handoff so that we are handing off a quality product and preparing them for future development.

### Action Items
- [x] Create three issues for the phases of spell checking
- [ ] Add a `ready for product` label once issues are sub issues are closed and see if we have achieved the objective or do more issues need to get made
- [ ] add a bullet list to the slide that communicates to the stakeholders what we did.

### Resources/Instructions
- This link of GHAs that do spell checks might help: https://github.com/marketplace?type=&verification=&query=spell
- Issue from HfLA website team on same: https://github.com/hackforla/website/issues/3546
- [Bonnie's Query for spell checkers](https://github.com/marketplace?type=&verification=&query=spell)
- Suggestion of a specific spell checker (provided by Fang) [eslint-plugin-spellcheck](https://github.com/aotaduy/eslint-plugin-spellcheck)

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide 413](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g33fd44e1e89_2_30)
- Release Deck
   - [YYYY-MM-DD Release Deck, slide 413]

**Comment by KPHowley** [comment]
https://typosaur.us/  - Check out this!

**Comment by KPHowley** [comment]
Putting this back in the Backlog so we can check after Dev freezes.  We want to also make sure to check the tool tips.

**Comment by fyliu** [comment]
This may be worth looking at. https://github.com/aotaduy/eslint-plugin-spellcheck

**Comment by ExperimentsInHonesty** [comment]
It's been a while since this issue was written and I have been working with the hack for la website team.  Here is what I think about this issue now.  

This issue needs to be turned into an epic with three issues

Why the change.  In order for the spell check to not throw a ton of false errors, you have to add things to an excluded or ignore list, which also takes time to create.  It would be worth it, to do this, but this is a big undertaking.  I would rank this in the following way

### Must Have priority
Do a one time spell check now
and then another one before handover

### Could Have
In this order
1. Run a check on the whole repo and put all the errors in a spreadsheet
2. creating an ignore list
3. Install a linter on the PR checks
4. add info about a VS code extension that team members can install

**Comment by angelaliao1231** [comment]
broken down into smaller issues
- Must have: [immediate spell check ](https://github.com/hackforla/tdm-calculator/issues/2204)
- Must have: [spell check before site handover](https://github.com/hackforla/tdm-calculator/issues/2205)
- Could have: [additional add-ons](https://github.com/hackforla/tdm-calculator/issues/2206)

**Comment by ExperimentsInHonesty** [comment]
This epic needs a revision to reflect the new issues we have made and the order we want them done in.
- #2204 
- #2205 
- #2206

**Comment by ExperimentsInHonesty** [comment]
Create more issues
- Spelling: Exclude list: Add all the project specific words currently identified by linter
- create a template: Update Exclusion list to include words caught in each new PR (not actual misspellings)
   - add your issue to the epic once created
- Dev: Create GHA to update the PR with a comment, with instructions for what to do when the linter catches "spelling errors"
   - check epic for outstanding issues so you don't duplicate
- Spelling: Exclude list: Export all text from the database (tooltips, etc.) so that we can identify what additional words to add to the linter

**Comment by ExperimentsInHonesty** [comment]
We need another epic to track the exclusion activity.

**Comment by lola3736** [comment]
@ExperimentsInHonesty you assigned this issue to yourself, is this accurate, seems this should be in the "Ice Box" (moved) given the dependency.
