### ISSUE TITLE
Make link styling consistent throughout app

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#718]
We need to make all the links consistent on the website. 

### Tasks
- [x] Update CSS files 
- [x]  Make links consistent blue color 
- [x]  makes link underlines

### Reference for color:

![Screen Shot 2021-03-31 at 7 24 27 PM](https://user-images.githubusercontent.com/49739276/113234862-f62e3c00-9256-11eb-84e8-a3b33f79eed3.png)

**Comment by jahpe777** [comment]
Made link styling consistent throughout app #718
