### ISSUE TITLE
Refactor: miscellaneous

### ISSUE THREAD

**Issue by nclairesays** [hackforla/tdm-calculator#740]
### Overview

We need to do some code cleanup to make the project easier to manage for current and future development.

#### Note from Claire
I've noticed some code that can be refactored and cleaned up, which will make our codebase easier to manage. Adding them to this issue as I go. If the issue is big/it has greater user value, I will create separate issues. 

### Action Items
- [x] Create an issue for each unchecked box 
- [x] Meet with Claire to get details about what is missing
- [x] If its a refactor issue find out if its CSS, HTML, JavaScript, or other
- [ ] make sure release note is labeled

### List of Issues noted that need new issues created
- [ ] #944 - Need Claire input
   - [x] level
   - [x] priority
   - [x] role
- [ ] #945 - Need Claire input
   - [x] level
   - [x] priority
   - [x] role
- [x] Use recommended format for our Routes: "The recommended method of rendering something with a <Route> is to use children elements" (instead of render or component). From [React Router documentation](https://reactrouter.com/web/api/Route/route-render-methods). Using component..."you would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. "
- [x] Fix error message for when there is no loginResponse (e.g. if the database is not running).
- [x] Fix PropTypes; including calcValue number/string mismatch due to user-defined strategies having a default value of null
- [ ] #946 - 
   - [x] level
   - [x] priority
   - [x] role
- [x] fix styling on login/registration; including sidebar/make auth related pages consistent (resetPassword vs forgotPassword)
- [ ] #947 - 
   - [x] level
   - [x] priority
   - [x] role
- [x] Fix various console warnings
- [x] Updating heading styles --> addressed as part of #789
- [ ] #948 - CSS
   - [x] level
   - [x] priority
   - [x] role
- [ ] Move app.scss and calculations.scss into jss  --> created new issue https://github.com/hackforla/tdm-calculator/issues/790
- [ ] #949 - 
   - [x] level
   - [x] priority
   - [x] role
- [x] Fix tests --> created new issue #798
- [ ] #950 - HTML
   - [x] level
   - [x] priority
   - [x] role
- [ ] #951 - CSS
   - [x] level
   - [x] priority
   - [x] role
- [ ] #952 - 
   - [x] level
   - [ ] priority
   - [x] role
- [ ] #943 - 
   - [x] level
   - [x] priority
   - [x] role

**Comment by ExperimentsInHonesty** [comment]
Hi @nclairesays,  During our weekend meeting we were reviewing the board, and after looking at this issue @entrotech has agreed it would be good to break out each of these into a new issue because some of these will be perfect for new developers.  In order to save you the time of making each issue, @jackrinjames  is a new pm on the project and he will make them and then meet with you to get any details he is missing.
