### ISSUE TITLE
Discussion items: checklist of information required

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#784]
### Overview
We need to have a check list for users before they have to start using the calculator so that they know what information to gather/bring.

### Action Items
- [x] Discuss whether we need to add a feature that informs the user what information is needed to use the TDM calculator
- [ ] Link in Resources section all the materials from the Usability Testing
- [ ] Gather Checklist draft from materials used during Usability Testing (insert into comments below)
- [ ] Review draft with product

**Comment by ExperimentsInHonesty** [comment]
@KPHowley @VJ1285 @anamsha did the research reveal that this issue seems necessary?


Including you for FYI: @seenaiype

**Comment by KPHowley** [comment]
A duplicate issue for this exists. #875, closing this issue
