### ISSUE TITLE
Change BlueLA Car Share Memberships to +1 point bonus

### ISSUE THREAD

**Issue by awikstrom-ladot** [hackforla/tdm-calculator#791]
### Overview
Change the BlueLA Car Share Memberships option to be a +1 point option only if the applicant selects Car Share Memberships.

It is currently possible to select both Car Share Memberships and BlueLA Car Share Memberships. We'd like to have BlueLA only appear as an option if Car Share Memberships is selected.

### Tasks

- [x] Change the two measures: "Car Share Memberships" and  "BlueLA Car Share Memberships" to a single drop down menu called "car share membership with the options:   "N/A", "third party operator membership", and "BlueLA"
- [x]  Make points to  3 for " third party operator membership" and 4 for "BlueLA"
- [x] Display possible points of 3-4
- [x] Change Tooltip to "Offer an annual car share membership for at least 50% of residents or employees. Membership to Blue LA Car Share earns an additional point due to the program's priority on promoting equity in selecting the service area. Consult LADOT in determining if the project location is eligible for Blue LA membership based on the service area. '
- [ ] Automatically select "Electric Vehicle Bonus"  if "Blue LA car share membership" is selected.

**Comment by Dsomers74** [comment]
This means possible points earned would be 4

**Comment by KPHowley** [comment]
@Dsomers74 @awikstrom-ladot  - double checking the functionality on this. @entrotech  - including you as well for logistics

From my view we might be able to achieve this with a drop down. My suggestion would be making that so the measure is "Car share memberships" and then the two options could be something like "third party operator" which would be 3 points  and then "BlueLA" which would be 4 points. We would also need to collapse the tool tip definition into one. 

Otherwise we can make a "BlueLA Car Share Memberships" grayed out until "Car Share Memberships" is selected and then this can be one additional point (if that is what your are envisioning).  I think this may be a bit confusing though, and people may not realize they are connected. 

Let me know if that would work or if I'm missing something!

**Comment by Dsomers74** [comment]
@KPHowley @entrotech - Agreeing that we should go with a drop-down option with "third party operator membership" and "Blue LA car share membership" as listed as the two choices.

The tooltip could be revised to read: "Offer an annual car share membership for at least 50% of residents or employees. Membership to Blue LA Car Share earns an additional point due to the program's priority on promoting equity in selecting the service area. Consult LADOT in determining if the project location is eligible for Blue LA membership based on the service area. '

Also, is it possible to automatically select the "Electric Vehicle Bonus" under the "Car Sharing" menu if "Blue LA car share membership" is selected?

**Comment by KPHowley** [comment]
@Dsomers74  - I think that will be possible, and The clarifications make sense to me!

**Comment by KPHowley** [comment]
@Dsomers74 - we were just going over this and if we have "Electric Vehicle Bonus" selected automatically with "BlueLA" users would essential be getting 5 points for that measure, is that the intended functionality?

**Comment by KPHowley** [comment]
We did verify that we should enact: 

Automatically select "Electric Vehicle Bonus" if "Blue LA car share membership" is selected.

@entrotech
