### ISSUE TITLE
Automatically calculate and add Reduced Parking Supply TDM points if project is providing less parking than the Citywide Parking Baseline

### ISSUE THREAD

**Issue by Dsomers74** [hackforla/tdm-calculator#831]
### Overview
It would be helpful to show any eligible TDM points when a user enters their parking, so they see TDM point values change by entering different range of parking under the Citywide Parking Baseline. 

### Action Items

- [x] Automatically calculate and add the TDM points for Reduced Parking Supply if project is providing less parking than the Citywide Parking Baseline. 
- [x] Assign the TDM point value based on the percentage of parking reduced under the Citywide Parking Baseline. 
- [ ] Determine how to tell user that points were automatically assigned

### Resources/Instructions
This is not a high priority action, and can be completed after the public release.

**Comment by KPHowley** [comment]
@Dsomers74  - This was something that was brought up in our user testing as well!

**Comment by seenaiype** [comment]
Is this the same as - Determine if Reduced parking should be automatically checked #882

**Comment by seenaiype** [comment]
Discussed with LADOT (09/28) 

- [ ] have the strategies page show the points achieved automatically for reduced parking supply, based on parking provided on page 2.
- [ ] should the user be able to change the reduced parking manually - should be set to read only (greyed out) but have the ability to see the list of strategies
- [ ] User need to go back page to update the parking - design on how to capture (tool tip maybe) 
- [ ] show the shopping cart based on the points captured on parking provided page
- [ ] validation on the parking spaces - should allow 0 parking spots
- [ ] ADA spots - to be confirmed
- [ ] Design review to be done with LADOT

![image](https://user-images.githubusercontent.com/20568596/135179119-b0119709-f9a6-48bf-bf52-a758292d3919.png)

**Comment by ExperimentsInHonesty** [comment]
The conversation with David (stakeholder) ended up us needing to Mock up language changes and show to stakeholder next time.  David also mentioned having it flash to get their attention (but in a throw away comment kind of way), but we are not doing that.  We have discussed and dismissed doing screen flashes in the past.

**Comment by Reneedesigns** [comment]
Progress: Familiarizing myself with the Figma file. Working through recreating the screen in Figma with either a pop up option or text under the spaces box that denotes points added
Blockers: Don't have access to Calibri font in my Figma file. Wanted to ask at meeting if there is access to that.
Availability: Can work on it before next meeting
ETA: By next week

**Comment by Reneedesigns** [comment]
Progress: 2 option flows created https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5955%3A21040
Blockers: Getting further clarification from team
Availability: Open
ETA: Next week will have more edits

**Comment by Reneedesigns** [comment]
Progress: Updated both options with more specific language on alert of pts added, put color back into grayed out Reduced Parking Supply on pg 4
Blockers: Are we wanting to keep language of "Provided parking/Baseline" or does that need to be clarified? 
Availability: Open
ETA: One week

**Comment by Reneedesigns** [comment]
Progress: Added reduced parking percentage tooltip to page 3 design to include reduced parking points, added a reduced parking supply possible pts under parking spaces, expanded pts earned explanation for pg 3
Blockers: Ask if we want percentages to be the same or different between pg. 3 and 4

**Comment by Biuwa** [comment]
Please attach updated Screenshots to your comments @Reneedesigns

**Comment by Reneedesigns** [comment]
![Reduced Parking popup](https://user-images.githubusercontent.com/99779174/168840943-626b0726-3c8a-45d3-aed0-63c4b11924e2.png)
![Reduced Parking box](https://user-images.githubusercontent.com/99779174/168841047-fe800044-40be-4454-81e5-1f44a95d75f5.png)

**Comment by ExperimentsInHonesty** [comment]
Provide the language to Xander so that he can edit/approve it.

**Comment by Reneedesigns** [comment]
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6115%3A2099
![V4-side calc button](https://user-images.githubusercontent.com/99779174/170398839-a6cbef73-35b4-48b2-bb33-8fcbe31cc7b6.png)
![V4-side calc button 2](https://user-images.githubusercontent.com/99779174/170398854-cc664003-846f-4e47-a8b0-1dc2927c3f9f.png)
![V4-side calc button 3](https://user-images.githubusercontent.com/99779174/170398869-c828775c-7f6e-479b-b274-eaa57285b294.png)

4

**Comment by Reneedesigns** [comment]
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6117%3A2100
![V5-Calc on bottom 1](https://user-images.githubusercontent.com/99779174/170399282-2de7ea6e-f7c3-4254-8fc7-ddc3a09d3054.png)
![V5-Calc on bottom 2](https://user-images.githubusercontent.com/99779174/170399293-1619e338-ec1f-4bf8-bef2-2f3a5764b4e2.png)
![V5-Calc on bottom 3](https://user-images.githubusercontent.com/99779174/170399301-a1ca580d-9722-4f21-92cd-d288e995539e.png)
1

**Comment by Reneedesigns** [comment]
https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6117%3A2100
![V6- Calc in advance place 1](https://user-images.githubusercontent.com/99779174/170399758-ae98c47a-8470-4c6a-a6ef-9c04af72e2b4.png)
![V6- Calc in advance place 2](https://user-images.githubusercontent.com/99779174/170399771-2d718207-e699-49cd-b85b-445c30de5834.png)
![Uploading V6- Calc in advance place 3.png…]()
1

**Comment by Reneedesigns** [comment]
Options 2, 3, and 4 for transition/trigger option of Reduced Parking Supply

**Comment by Reneedesigns** [comment]
Revised option 2 (calculate button next to "spaces" box)

https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=6133%3A20993

![Calc side button](https://user-images.githubusercontent.com/99779174/170802772-4d35e2e4-10d1-4b4b-96ba-5d941912f629.png)

![calc side button 2](https://user-images.githubusercontent.com/99779174/170802837-9c16447b-bac2-47c0-a238-bd8b02dafc74.png)

![Calc side button 3](https://user-images.githubusercontent.com/99779174/170802840-481c998a-2858-4ecd-8c8e-3bdb4347b8ed.png)

**Comment by entrotech** [comment]
Created a development Issue #1186 for @Reneedesigns tooltip changes.

Remaining things to do are:
- Decide on wording of the notification box in the sidebar - this should be resolved when Bonnie discusses [this document](https://docs.google.com/document/d/1mrSniJGLqQ-pxqes9hR0rQoFp7619PElCo_zMCCvOQk/edit#heading=h.nyn0inkxu893) Xander next week.

- As described above, we wanted to consider two options for triggering the calculation:
  - Trigger the calculation as the user enters characters in the Parking Provided text box, which was implemented on Issue #1164, or
  - Trigger the calculation when the user presses a separate "Calculate" button (described as Option 2 above), which was demonstrated as a possible option to the stakeholders on 5/31, and they seemed to like.

**Comment by SMR9220** [comment]
As per Emily and Xander, the wording of the notification box in the sidebar should be, "Automatically earned 2 points using the TDM Strategy Reduced Parking Supply for reducing parking by 10-24% below the Baseline." Please refer to [this document](https://docs.google.com/document/d/1mrSniJGLqQ-pxqes9hR0rQoFp7619PElCo_zMCCvOQk/edit#) at bookmark #1 for clarification with that specific example.
