### ISSUE TITLE
Create Detailed/In-depth video for users

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#866]
### Dependency
- [ ] When the application is ready for people to start using it (has a solution for what happens on the last page/submission, etc. which is going to a form.  [See all issues using label: p-feature - Submit Snapshot](https://github.com/hackforla/tdm-calculator/labels/p-feature%3A%20Submit%20Snapshot)) https://github.com/hackforla/tdm-calculator/issues/1652
- [ ] My projects updates are all in prod 
- [x] #875
- [x] ~#874~
David said that they anticipate significant changes to the strategies based on the feedback they are getting. So we will hold off on this video until we get the changes.

### Overview
We need to add a detailed/in-depth video that helps the user understand how to navigate the web pages and also how to access tooltips.

### Action Items
- [ ] Define ideal length of video
- [ ] Define what features and functions of the app will be covered in the video
   - [ ] see the comment below for some notes about what people were confused about early in testing https://github.com/hackforla/tdm-calculator/issues/866#issuecomment-1304592072
- [ ] Define where the tags will go (so that the video can play on specific pages the user is on by the time stamp). 
- [ ] LADOT to review script
- [ ] Make an in-depth/detailed video
- [ ] Add tags to the video 
- [ ] review with stakeholder

#### Slides
- [Staging Deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg)
   - [Staging Deck, slide 866](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g3389954eb7d_35_12)
- Release Deck
   - [YYYY-MM-DD Release Deck, slide 866]

**Comment by ExperimentsInHonesty** [comment]
David said that they anticipate significant changes to the strategies based on the feedback they are getting.  So we will hold off on this video until we get the changes.

**Comment by ExperimentsInHonesty** [comment]
Emily and Alexander are we ready to make this or should we hold off until approval from Planning Commission

**Comment by Biuwa** [comment]
Emily says 'Keep on hold till after the subsequent User testing and after the City-Attorney has spent some time with the ordinance, which might be at the end of the year'

**Comment by ExperimentsInHonesty** [comment]
At one point we thought the video would address these issues.  We hope that we have addressed these issue in the app itself.  But its a good list to reference when making a script for the video.

### Notes
The video should be able to address the below issues from the usability testing
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

- [ ] Bonus package information is confusing, not sure what it applies to and how it fits into the flow of everything. 
- [ ] Users were unsure of what to do at this step as it is informative rather actionable. 
- [ ] People do not know there is a tool tip for every single row on this page. They are missing the disclaimer at the very top of the page. 
- [ ] Bonus package information is lost and hard to find
- [ ] People are not quite sure what the point of this page is. Not sure that one can use this page to see the different options they may take to meet the TDM requirements.
- [ ] General confusion on what information is actually required (e.g., how much detail is needed for project description). 
- [ ] Users are confused about what to do with the information presented on this page. 
- [ ] User is unsure where these numbers came from, especially the Target Points. 
- [ ] Tooltip information is lengthy and confusing
- [ ] Users unclear what to do if they did not succeed, as this is not displayed

**Comment by pmeda12** [comment]
Here are some thoughts I have on length, content, and placement.

Length:
-This video should not be very long if its purpose is to explain tooltip visibility and function
- Few seconds max since there are 2 types of tooltips (hover over, and clickable)

Content:
-Check common areas of difficulty in tooltip visibility
-Research study where we ask one group to go thru the site and another to go thru site with the video

Location:
-A/B test design preferences in which we show users images of the site with varying placements of the video.

**Comment by Jane4925** [comment]
Clarifying question: are we aiming to 1) have a whole run down video that walk through a test case project and tour the site, or 2) short videos that focus on particular pain points?

**Comment by mojimoh** [comment]
@Jane4925 @pmeda12 The intent of the video is to have a complete run through of the site features using a test case to tour the site.

**Comment by Jane4925** [comment]
@pmeda12 will start making a rough draft for outline

**Comment by pmeda12** [comment]
-Checklist
-Explanation of visual design
   --When hovering over clickable item, it changes visually from x to y
-How to use the following functions:
   --Reset page / reset project
   --Top menu bar
   --Save project
-Pain points to clarify
    --Purpose of bonus package
   --How strategy selection factors into sidebar

**Comment by pmeda12** [comment]
https://docs.google.com/document/d/1fu1RidWoyNoHK_2HR4dapVPAEQvKB_fB0BiGTvz_Lks/edit

**Comment by ExperimentsInHonesty** [comment]
Moving up to Priority: Should Have because of the problem with users not seeing tooltips even though we have tried 
- bolding on hover
- changing color on hover
- adding a box on page 1 that explains how to get more information

**Comment by Jane4925** [comment]
Per notes from [04/05/2023 team meeting] (https://github.com/hackforla/tdm-calculator/issues/1311#issuecomment-1498346806), here are some current thoughts and questions:
- "Where would this video be viewable?": thinking that Youtube is a suitable media if LADOT has an official channel and agrees to create a designated playlist. We can also link the tutorial videos on the TDM Calculator site under the FAQ page or inside specific tooltip or page. 
- "break it down, so it's easy to implement": can we be a bit more specific on how to further break it down?

**Comment by Jane4925** [comment]
If we still want to do a complete run-down tutorial video using test cases, then Youtube might be the most suitable media. We can set up the ["chapter"] (https://support.google.com/youtube/answer/9884579?hl=en#:~:text=Video%20Chapters%20break%20up%20a,rely%20on%20automatic%20video%20chapters.) inside the complete video, or have a playlist including shorter videos breaking down very page.

If we want to do short video clips, we can still post on the Youtube and link/embed those videos on the FAQ page along side the specific question, or inside tooltips, or somewhere on each page within TDM Calculator site. If we don't want to post the short video clips on Youtube, I don't know how feasible it is to embed them on the website... probably a question for Dev team. 

A question though, when do we expect this to start?

**Comment by Biuwa** [comment]
This issue is in ice box until we finish implementing solutions for the tooltips
