### ISSUE TITLE
Addressing Multiple AINs - Issue from Usability Testing 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#867]
### Overview
During the usability testing (Row 11), users were unsure how to input information for projects with multiple addresses

### Action Items

Stakeholder and PM:
- [x] 1. Confirm with LADOT whether a project can have multiple addresses or not. If the project cannot have multiple addresses then the below doesn't apply. 
- [x] 2. if the project can have multiple addresses then ask LADOT whether the users need to input multiple addresses or just one address would suffice
- [x] 3. if a project can have multiple addresses and the users do not need to enter multiple addresses then we can just add a tick box that the users can check to note that projects have multiple addresss
- [x] Create front end ticket when UI/UX tasks are done

_Determiniation after stakeholder meeting : Address - update to say primary address, a user can provide a range of address, but do nit allow for mulitple input boxes . AIN/APN - ability to add multiple APN (can be up to 10 APN), we need to design for multiple input boxes_

UI/UX:

- [x] Create Mockup for new /calculation/1 page in Figma
- [x] Change "Address" input label "Primary Address(es)"
- [x] Determine method for adding multiple AINs and add to design (see resources)
- [x] Specify flow for adding multiple AINs (i.e. valid, invalid, edit, etc.)
- [x] Present mockup for review
- [x] determine How the summary Page would be updated for the change

### Resources/Instructions

AIN number field needs to allow multiple AINS (medodology where when you add one, it lets you add another) This can be done through something like a button that asks if you have another AIN and lets you add more (up to 10 for now)
[see an example](http://civictechindex.org/join-index?changeValue=TopicTag&currentTags=hack-for-la&currentTags=civictechindex&currentTags=code-for-all&currentTags=code-for-america&currentTags=community-of-practice&currentTags=product-managment&currentTags=product&displayState=TopicTag&fullRepositoryUrl=https%3A%2F%2Fgithub.com%2Fhackforla%2Fproduct-management&orgName=&repositoryName=product-management&repositoryUrl=https%3A%2F%2Fgithub.com%2Fhackforla%2Fproduct-management&topicSearchError=&userTags=555-55-5555&value=no)

https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by VJ1285** [comment]
@Dsomers74 - One of the issues that were raised during our usability testing was that what should do the users do when a project has multiple addresses? I had the following questions with regards to this issue?

- [ ] Can a project have multiple addresses?

- [ ] If yes, does the user need to enter all the addresses or only one address is sufficient?

- [ ] If only one address is sufficient, which address they should input?

- [ ] If the user needs to enter multiple addresses, then do they need to enter all the addresses related to that project?

You can discuss this issue further with @ExperimentsInHonesty & @KPHowley during the next meeting.

**Comment by ExperimentsInHonesty** [comment]
LACP is less concerned with multiple addresses, ,they are more likely to go off the AIN number.  There are projects that span several AIN numbers.  And they would need all the AIN numbers

LADOT would like Addresses since they use them for tracking.  

"Primary Address (can be a range)"

**Comment by ExperimentsInHonesty** [comment]
requirements for design
AIN number field needs to allow multiple AINS (medodology where when you add one, it lets you add another )
[see an example](http://civictechindex.org/join-index?changeValue=TopicTag&currentTags=hack-for-la&currentTags=civictechindex&currentTags=code-for-all&currentTags=code-for-america&currentTags=community-of-practice&currentTags=product-managment&currentTags=product&displayState=TopicTag&fullRepositoryUrl=https%3A%2F%2Fgithub.com%2Fhackforla%2Fproduct-management&orgName=&repositoryName=product-management&repositoryUrl=https%3A%2F%2Fgithub.com%2Fhackforla%2Fproduct-management&topicSearchError=&userTags=555-55-5555&value=no)

Address should be a primary address or a range and they should indicate.

**Comment by seenaiype** [comment]
Discussed with LADOT today (09/28)

1. Address - update to say primary address, a user can provide a range of address
2. AIN/APN - ability to add multiple APN (can be upto 10 APN)

No validations happening on these fields.

**Comment by jackrinjames** [comment]
Discussed with LADOT (11/2)

- Dave chose option to have entries stay within text box so it's intuitive that the information has been added.

**Comment by cduong5** [comment]
![Frame 8](https://user-images.githubusercontent.com/82553907/141228296-8d2791e4-2560-42d4-a75e-deea5589ec44.png)
Updated flow so that users are shown a prompt after they type in the AIN/APN #

**Comment by cduong5** [comment]
[](url
![Frame 7](https://user-images.githubusercontent.com/82553907/141228642-16971fc9-019d-409b-9d33-34e5834323cd.png)
)

Mockup for error messages on input forms and required fields

**Comment by cduong5** [comment]
![Uploading Frame 7.png…]()
Mockups for multiple AIN/APN #s

**Comment by cduong5** [comment]
![Uploading Frame 7.png…]()
Mockups for multiple AIN/APN #s

**Comment by cduong5** [comment]
![Frame 7](https://user-images.githubusercontent.com/82553907/141228996-416ae35a-67d0-4fa4-8b52-1a884ba893d2.png)

Mockup for errors messages in text fields and indicators for required fields

**Comment by cduong5** [comment]
![Frame 61](https://user-images.githubusercontent.com/82553907/141414262-92cf06c0-f4d7-436f-a5be-727f4880337a.png)

Removed green as an option since it had accessibility issues against the white background. Mockups for new tag color options: gray and lighter navy blue.

**Comment by cduong5** [comment]
![Ideation v 2](https://user-images.githubusercontent.com/82553907/141842041-5c1f1e4e-05fd-42af-8cdd-a34cc043bd89.png)
![Frame 55](https://user-images.githubusercontent.com/82553907/141842059-340584e8-d262-4846-bd14-81a8367c87f8.png)

Mockup for final tag color, light gray. Used shadows for accessibility against white background.

See prototype here: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4806%3A17157&scaling=min-zoom&page-id=4687%3A17152&starting-point-node-id=4806%3A17157

**Comment by ExperimentsInHonesty** [comment]
Notes from meeting: David and Emily said all the AINs don't have to appear on the final page.

**Comment by seenaiype** [comment]
One more thing - no particular limits to the # of AIN's that can be entered on the the first page. But, the final/summary page can be limited to couple of them with an indication that there are more.

**Comment by KPHowley** [comment]
@cduong5 @Shaeeka  - Just reviewing and i think we're close to sending this to Front End - did we have a message that was supposed to display in the text box that was something link "Click to add Multiple AIN's"

**Comment by cduong5** [comment]
![Frame 55](https://user-images.githubusercontent.com/82553907/142352749-3880518d-1060-4667-b730-92e3801b1666.png)
Created prompt within text field for users to "Type to add another" each time they finish adding a tag. Typing function should remain active as users add consecutive tags. 

See mockup here: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4687%3A17152

See prototype here: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4806%3A17157&scaling=min-zoom&page-id=4687%3A17152&starting-point-node-id=4806%3A17157

**Comment by cduong5** [comment]
Created prototypes showing the flow of entering multiple AINs.

**Comment by cduong5** [comment]
@KPHowley accidentally closed this issue, can we reopen it?

**Comment by cduong5** [comment]
Added more detail to the flow.
New prototype: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5132%3A18439

**Comment by seenaiype** [comment]
To create a Dev issue for this

**Comment by seenaiype** [comment]
#1010
