### ISSUE TITLE
TDM Summary Page redesign 

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#873]
### Overview
Redesign Page 5 - TDM Summary page

Action Items:
- [x] Create Mock-up (or mock-ups) for Final page
- [x] Update the title to show - Project Name - Address
- [x] Switch the target and earned points, so its consistent with the sidebar
- [x] Move the project level and parking provided baseline % to the top section of project details, maybe as an extra column after Parcel and Version #
- [x] Update _Version #_ to  _Alternative #_
- [x] Results to only show the points section, Color code the numbers to red and green, based on target reached
- [x] Move _Land Use_ section to _Project Specifications_
- [x] Add a title for _Parking details_ for the baseline parking and Parking provided

- [x] Message around target point achieved or not. 
                > If Target points are achieved, update the success toast to state. That they can Print and submit this page for getting their permit.
               > If target is not achieved - Come up with best wording to notify users they have not meet their target points and can return to select more strategies
- [x] Layout to be - Project Name, Project Details , Results, TDM Measures Selected, Project specifications - Land use and Parking 
- [x] Add a button for Save & Print
- [x] Keep formatting and color/style in line with other notifications on page
- [x] Show design or designs to product team for visual review

![image](https://user-images.githubusercontent.com/20568596/128176371-ae971118-1a9c-447d-bae8-34ad932fb206.png)

-------------------
Below ate the issues that need to be addressed on Page 5

Row 28 - Users unclear what to do if they did not succeed, as this is not displayed
Row 29 - Users unsure as to whether the project level is important and why the "parking provided/baseline" was emphasized 
Row 30 - Users are confused about what to do with the information presented on this page
Row 31 - Users are concerned about the approval process (Are they really "good" after going through the calculator)

### Ideas
Row 28 - Need to convey via color coding and text that the user met the target points
Row 29 -
Row 30 -
Row 31 - Need to convey to the users that the information will be reviewed by LADOT prior to approval.

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by KPHowley** [comment]
@VJ1285 - I believe all of this had been addressed with other issue  - let me know if anything was not turned into it's own issue.

**Comment by shinhope** [comment]
draft completed
![tdm summary page](https://user-images.githubusercontent.com/79497980/128270725-ab9aa0fe-52a3-462c-bbf9-85429bd25a24.png)

**Comment by shinhope** [comment]
**New summary pages (but still using old sidebar, not new one)**

Target points achieved:
![VER 6  tdm-summary](https://user-images.githubusercontent.com/79497980/128555184-6b1d2487-5a6f-448c-943a-5e2db4e4015b.png)



Target points NOT achieved:
![VER 5  tdm-summary](https://user-images.githubusercontent.com/79497980/128555189-bbd1a495-63ea-438a-9b0a-e9914ef2976a.png)

**Comment by seenaiype** [comment]
@shinhope , couple of minor tweaks. 

- Change the Parcel#(AIN) to AIN (Parcel#) , to be consistent with the first page
- Move the Project Level and Parking provided/baseline under the Project specifications Above land use
- Increase the size of the notifications a little 
- Change the toast to  
           > Success - "You have successfully earned the target points. Please, print and submit"
           > Failure - " You have not reached the target points. Please, go back and review other strategies"
-  Change the button to say - "Save and Print"

-

**Comment by shinhope** [comment]
![VER 5  tdm-summary](https://user-images.githubusercontent.com/79497980/128766911-9b049e0b-f931-437e-bd24-57da69bb0ba0.png)
![VER 6  tdm-summary](https://user-images.githubusercontent.com/79497980/128766917-a460f735-fc12-436f-8ac3-f88f9821bfd7.png)

**Comment by seenaiype** [comment]
Hope, On the error page, can you change the comment for failure. 
- > Failure - " You have not reached the target points. Please, go back and review your strategies"

**Comment by shinhope** [comment]
![VER 5  tdm-summary](https://user-images.githubusercontent.com/79497980/128967029-5623aeaf-0201-4403-a018-3e4303468695.png)

**Comment by KPHowley** [comment]
@seenaiype @shinhope - We discussed this on the meeting on 8/14/21 - 

We have a few things we need to address in the Figma file:
- [ ] Make sure that the colors (red and green) are in line with our style guide and rest of the pages.
- [ ] Make the success and failure wording slightly larger to emphasize 
- [ ] Make sure the Figma file is presentable and that  all of the sections with headers are grouped together or represented by separate images:"Results", "TDM Measures Selected", "project selections" and the Name/Address section.  This is so we can review priority with stakeholders and adjust in real time on the Figma file.

**Comment by shinhope** [comment]
![VER 5  tdm-summary](https://user-images.githubusercontent.com/79497980/129645491-20720f07-a817-4d53-a4cd-0c8bde3efe95.png)
![VER 6  tdm-summary](https://user-images.githubusercontent.com/79497980/129645492-a32c5045-3ae1-4ece-b0f9-321f46f64b66.png)

**Comment by shinhope** [comment]
Not sure what you mean for the Figma file

**Comment by shinhope** [comment]
Under //Summary Page - New, I grouped the sections and placed them on the white backgrounds. They are easily moved around on the empty summary page on the left.

![image](https://user-images.githubusercontent.com/79497980/129646962-f9d8e745-66c5-414b-b472-5873319e9811.png)

**Comment by ExperimentsInHonesty** [comment]
@shinhope thank you for your work.  It was VERY useful in todays meeting with the stakeholder.  

_Small note: The images above have the old left side panel with the smaller numbers.  Please always use current version of site in mockup unless you are changing an element and that is what you want feedback on._

**Comment by shinhope** [comment]
@ExperimentsInHonesty Are you referring to this left side panel?
![image](https://user-images.githubusercontent.com/79497980/129812890-c0834f58-77e8-4e2d-9a9e-16e976430eb8.png)

**Comment by ExperimentsInHonesty** [comment]
@shinhope yes

**Comment by ExperimentsInHonesty** [comment]
LADOT has indicated how they want page 5 changed where we 

1. remove the subheaders from the project specifications section
2. change the name from PROJECT SPECIFICATIONS to Project Details.
3. move the parking provide/baseline percentage line down below the other parking items.

**Comment by Akheal** [comment]
4. Make the verbiage of line items on the summary page consistent with the project. 
eg: Baseline Parking should be Citywide Baseline Parking

**Comment by shinhope** [comment]
![VER 5  tdm-summary](https://user-images.githubusercontent.com/79497980/129839377-7d832dc5-526b-4564-9172-da23943362d4.png)
![VER 6  tdm-summary](https://user-images.githubusercontent.com/79497980/129839383-12e1fe97-ca31-40e3-9263-ed40cea2ed7f.png)

**Comment by shinhope** [comment]
![VER 5  tdm-summary](https://user-images.githubusercontent.com/79497980/129839514-723bb171-661e-4daf-96c2-aed68b8c65aa.png)
![VER 6  tdm-summary](https://user-images.githubusercontent.com/79497980/129839519-d68c5baa-b683-4b1a-bbdc-400da7bf7831.png)

**Comment by shinhope** [comment]
@ExperimentsInHonesty Is that what you meant by removing subheaders?
@Akheal I'm not sure what other verbiage is incorrect. Do you have a screenshot or something from the figma that has the current wording?

**Comment by Akheal** [comment]
@shinhope, I meant the line items listed on the summary page should be consistent across the other pages. In your fresh screenshots above you got it corrected.

**Comment by Akheal** [comment]
@shinhope highlighted two numbers under the project details that should be under earned points. currently, the earned points for these two show 0 pts but they should be actual selections. 

![image](https://user-images.githubusercontent.com/88067894/129843642-a4c5e1ed-4e56-49f6-b4d5-bb539cc3515f.png)

**Comment by shinhope** [comment]
@Akheal do you mean like this? 
![image](https://user-images.githubusercontent.com/79497980/130002089-cf9f7c73-dd7a-4e86-93c5-bce31d069dea.png)

**Comment by seenaiype** [comment]
Hope, lets revert back to the prior one for the condo units, we are not changing that from what is in production. Once done, can you box the item in figma with a green border, so the dev team can make the updates accordingly.

**Comment by shinhope** [comment]
![image](https://user-images.githubusercontent.com/79497980/130554990-b0d4aef4-ecf0-4287-b996-137e1814db92.png)

**Comment by seenaiype** [comment]
@Shaeeka , for this summary page. Can we also update on how the summary page would look for the User defined strategies, so the developers can update it accordingly. 

development ticket - https://github.com/hackforla/tdm-calculator/issues/850

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/131768006-3910d3a9-4bf0-4cf2-8a3d-7bfca0faa307.png)

**Comment by Shaeeka** [comment]
[Figma file ](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=1744%3A3531)

- Updated the color to match the style guide
- Fixed the spacing of the Project Detail section

![image](https://user-images.githubusercontent.com/88021166/131802116-0af5f433-b07f-4db8-9b1a-f664ff815624.png)

**Comment by Shaeeka** [comment]
Reposting Bonnie's comment from #850 
Bonnie

    Suggest limiting the colors on this page. The red color could be the orange color if we did an outline or the box that the number is in could be solid orange and the text could be dark blue

David

    change version number to Alternative #
    Case to be City Planning Case #
    add LADOT Case #
    add Project Description under Project Details header
    Move the address to the smaller font (similar to PARCEL #(AIN))
    everse the order of Parking Provided and Baseline Parking

Emily

    Limit the number of colors on the page (through outlines with the colors, keeping the text in the dark blue).

**Comment by Shaeeka** [comment]
Providing two layout options for the top information section and the Product description section.

Top information layout
![image](https://user-images.githubusercontent.com/88021166/133665614-f6fd3e6c-1e93-47e5-856f-c7ac5b43779a.png)


Product description 
Version 1
![image](https://user-images.githubusercontent.com/88021166/133665401-977b81d2-039b-4ede-9267-68ef6824ae32.png)
Version 2
![image](https://user-images.githubusercontent.com/88021166/133664889-a3fbcc73-1188-48b5-aedb-6dee676470df.png)

[Figma file](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4091%3A12803)

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/134773404-497f55ff-8150-4cec-9d54-89b1e63afd4b.png)

**Comment by seenaiype** [comment]
Displayed the updates to LADOT. 

1. The notification and the box looks good 
2. for the top section - option A accepted - Project Name : as a header
3. bottom section - option A accepted - Project description towards the last element

**Comment by Shaeeka** [comment]
Final Draft located at **Summary Page** below the 📐 **Draft Pages** in [**Figma**](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4189%3A15774)

![image](https://user-images.githubusercontent.com/88021166/135181844-78441518-887a-4fdf-9125-de9227000632.png)

**Comment by KPHowley** [comment]
@Shaeeka  - Closing as we have Created a front end ticket for this finalized design
