### ISSUE TITLE
Add a Checklist on page 1 to show users what information needs to be brought to the calculator

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#875]
### Overview
The users are unclear what information they need to bring to the calculator, and a checklist on page one will allow them to navigate the site more confidently. 

### Action Items

- [x] Create checklist of information needing to be supplied.  Use usability emails/landing pages as a resource, but this should be an explanation of the following pages on the calculator. 
- [x] Design Check list 
- [x] Create mock up of checklist with placement on page one. Investigate options such as adding to sidebar or using a popup. 
- [x] Present options to Product Management / Group 
- [x] Review options with stakeholders
- [x] strike through dependency on #866 
- [x] #1216

### Resources/Instructions

[Email sent to Users for testing the calculator](https://docs.google.com/document/d/1T2kdLIlo-_BamIH3m_WPiBhQh2ILhpv-L7BJ7afGMsw/edit?usp=sharing)
[Landing page for Usability interviews](https://sites.google.com/view/landing-pg-user-research-bf/resources)

**Comment by ExperimentsInHonesty** [comment]
add a "(checklist)" with a link to a checklist of all the data they will need for the calculator.

**Comment by cduong5** [comment]
@KPHowley "Landing page for Usability" interviews link doesn't work. Is there a valid link?

**Comment by cduong5** [comment]
Task flow 
![v 2 Task flow](https://user-images.githubusercontent.com/82553907/150241331-2672eb83-8b80-458c-bbef-25bbe0a6707c.png)

Checklist design
![Checklist design](https://user-images.githubusercontent.com/82553907/150244974-ef72fe4e-bfdc-4623-a692-27eb9d77c760.png)

Icon design
![Icon Options](https://user-images.githubusercontent.com/82553907/150241536-ecf4738b-be92-4b64-8406-2771dd9f7bd2.png)
-still determining which icon to use

Interaction flow
![Frame 37](https://user-images.githubusercontent.com/82553907/150241557-00e11992-028f-48f3-96d8-c8de959c15dc.png)

Design decisions
- **What problem this design solves:** users don't know what information they need to use the calculator and this design provides users with a list with that information so they can navigate the site more confidently.
- **How this affects the user:** this design functions as a digital checklist that helps users foresee what information is needed in the following pages, check off what they have, and save whatever they marked. This list is available on each page so the user has access to it at all times. 
- **Why this is better than the alternative:** an alternative solution was to put the checklist in the sidebar. However, doing so would add clutter to the list that already generates from users selecting TDM measures and, therefore, confuse users.

**Comment by cduong5** [comment]
@KPHowley @seenaiype Can you post the feedback you received for the design here?

**Comment by cduong5** [comment]
Added more description to the checklist box explaining its purpose and how to use it:
![Frame 40](https://user-images.githubusercontent.com/82553907/151268557-4f8db3c5-efdb-42ba-844f-3eb3753cdb93.png)

**Comment by cduong5** [comment]
@KPHowley @seenaiype @Shaeeka 
### Feedback from meeting 01/26/2022
- checklist should appear once user navigates to create project page
- less interaction is better
- reword description 
- add resource link to help users find documents

### Redesign based on feedback
![v 2 Task flow](https://user-images.githubusercontent.com/82553907/151651248-c0adccac-47e7-45ee-8202-a728a7718902.png)
![Checklist design v 3 (1)](https://user-images.githubusercontent.com/82553907/151651252-8f9b7631-28e4-4960-a838-c05275fe3659.png)
Figma link: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/?node-id=4091%3A12802
Prototype link: https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5583%3A19555&scaling=min-zoom&page-id=4091%3A12802&starting-point-node-id=5583%3A19555&show-proto-sidebar=1

**Comment by seenaiype** [comment]
Review done on 02/08 - 

- [ ] indicate the last item as optional "p4 - Planned TDM strategies" 
- [ ] Subtext at the end, "Feel free to explore the calculator"
- [ ] Add the checklist under Additional resources in the About-Us page
- [ ] Have the link to About-Us page on the pop-up for future reference

Agreed, on that the pop-up as the first page loads for new projects

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/154395584-d9ae82bc-7094-4282-832c-4ac62705fda8.png)

- Please review if the link included in the design for the About Us page is the correct link
-  'Add the checklist under Additional resources in the About-Us page'- Can we create a new issue for this please since it involves a different page? 
[Figma link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5576%3A19713)

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/154815116-70c6bced-3530-485b-89b4-506ab4bc0fe3.png)

**Comment by ExperimentsInHonesty** [comment]
@Shaeeka At the stakeholder meeting, we discussed and decided to change the p2 sections to:

p.2      Planned floor area (sqft) for specific use types
- retail
- employment/office
- warehouse/industrial
- medical

p2.    Planned unit types/sizes for specific use types
- residential (dwelling units)
- hotel/motel (rooms
- school (students)
- arena/stadium/theater (seats)

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/156490776-d0c1951b-3f93-4e33-9293-f5a4ba1f2432.png)

![image](https://user-images.githubusercontent.com/88021166/156490889-f5cd75a9-a048-49ba-8fcb-9165fa858d9b.png)

[Figma Link](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5683%3A20479)
[Prototype Link](https://www.figma.com/proto/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?page-id=3331%3A11979&node-id=5683%3A20413&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=5683%3A20413)

**Comment by KPHowley** [comment]
Will discuss adding: "Check section 3 B of the [TDM PROGRAM UPDATE ](https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf)for exemption details" with stakeholders on 3/8 to notify users of exemptions

**Comment by KPHowley** [comment]
From issue #1042 

 At stakeholder meeting, David agreed with us putting the following
"
Check LAMC Section 12.26 J.3(b)(3) of the Draft Revised TDM Ordinance for exemption details.
"
The part that is bold is the link

**Comment by KPHowley** [comment]
Link: https://planning.lacity.org/odocument/1dc924ce-b94a-403b-afe0-17ba33b3dbe1/Draft_TDM_Ordinance.pdf

**Comment by Shaeeka** [comment]
Updated the pop up
![image](https://user-images.githubusercontent.com/88021166/158727639-2355c36e-82ac-4d6d-9a83-8cc6b624f3c7.png)

**Comment by seenaiype** [comment]
Minute change.. is the line space the same before p1 and after p4

**Comment by SMR9220** [comment]
The current Draft Revised TDM Ordinance link should be updated to the following URL:
https://planning.lacity.org/odocument/bb9114b3-29e3-423f-8b91-027afb242e63/Revised_DRAFT_TDMOrdinance_June2022.pdf

The wording of the display text should not change, only the link it goes to.

**Comment by ExperimentsInHonesty** [comment]
The checklist is live
