### ISSUE TITLE
TDM Terminology isn't inclusive for non-developers

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#877]
### Overview
Need to ensure the terminologies are inclusive for non-developers

### Action Items

- [ ] create a research draft -  to identify terms or words on the site and assets are not understood by people without any knowledge of real estate development/ city planning 
- [ ] do internal research at Hack for LA 
- [ ] Make a glossary list based on internal testing

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
add link on the about to program guidelines and call it Program Guidelines and Glossary

**Comment by Akheal** [comment]
@KPHowley Can you pls review this and add it to issue tracker?

**Comment by Biuwa** [comment]
Add a link to the Glossary at the bottom right next to Checklist, also to the FAQ page and the about page

**Comment by Biuwa** [comment]
#1240 is the design issue
