### ISSUE TITLE
Enhance Bonus Package info

### ISSUE THREAD

**Issue by VJ1285** [hackforla/tdm-calculator#880]
### Overview

Users were confused with the whole concept of bonus points when they were on a separate page. A mock up with the information added to Page 4, the Strategy page needs to be created. 

### Action Items

- [ ] determine options for displaying the bonus page on 
- [ ] Discuss with product management 
- [ ] Mockup 1- show a popup box on this page with the bonus info and integrated check box for selection 
![image](https://user-images.githubusercontent.com/20568596/128619367-cd7dfaf6-3c6d-403d-b41e-fc0753c7fbe7.png)
- [ ] Mockup 2 - Update page 4 (TDM strategies) to Add Bonus info on the top section. The bonus packages should have the details and integrated check boxes
![image](https://user-images.githubusercontent.com/20568596/128619314-0e64af1a-94de-4ba1-bf8c-046adc915c97.png)- [ ] Come up with Mock-ups and options
- [ ] Share with Product management and stakeholder review

### Resources/Instructions

Currently the bonus page information is only shown on a separate page when a user has a level one project. There are two packages which they can qualify, and both can be applicable to one project. 

One Bonus page conditionally shown:
![Screen Shot 2021-08-01 at 4 17 18 PM](https://user-images.githubusercontent.com/49739276/127788217-0854a67b-9674-4769-8c92-38d928b2e9c8.png)
Two Bonus pages conditionally shown:
![Screen Shot 2021-08-01 at 4 17 38 PM](https://user-images.githubusercontent.com/49739276/127788219-dbac5b06-d21a-4181-845a-a946b63808f1.png)

Strategies Page with bonus pages selectable. 
![Screen Shot 2021-08-01 at 4 17 49 PM](https://user-images.githubusercontent.com/49739276/127788221-6af5eaa2-4b1e-4804-897c-adb0f0af04b7.png)

**Comment by ExperimentsInHonesty** [comment]
David is open to other options, send to design for potential options including putting the content from the prior page on the top of page 4 with the check boxes integrated

**Comment by shinhope** [comment]
Progress: started mockups
ETA: by next Wednesday (Aug 18) latest

**Comment by shinhope** [comment]
Progress: mockups
Blocks: less time due to new internship
ETA: next Wednesday, August 25

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/150265391-e0caba51-297a-4cd2-88e9-86a0c632b1a3.png)
![image](https://user-images.githubusercontent.com/88021166/150265442-f86dda47-ddf5-4b71-9776-612039acdbf5.png)
[Figma link ](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5444%3A19449)

**Comment by seenaiype** [comment]
We currently have 2 packages - "Residential or employment package" and "School Package". This is based the inputs provided in page 2 - Residential or employment is enabled for project level 1 and school package is enabled when a school is selected.
 
![image](https://user-images.githubusercontent.com/20568596/150266573-759e7875-9df7-4e9b-ad61-0461df4bef7d.png)

**Comment by Shaeeka** [comment]
![image](https://user-images.githubusercontent.com/88021166/150646752-82436262-9f48-4562-a835-156f5b0524de.png)
![image](https://user-images.githubusercontent.com/88021166/150646776-90af5d88-8813-4d5a-9cd4-27abf35cf650.png)
![image](https://user-images.githubusercontent.com/88021166/150646807-43b15f6f-2866-4532-96a4-b3753388b80d.png)
![image](https://user-images.githubusercontent.com/88021166/150646822-be2573e8-e12a-42fa-b466-816a1cb156e8.png)

**Comment by ExperimentsInHonesty** [comment]
Shaeeka presented at our stakeholder meeting.  David approved and mentioned that he thinks this will address the confusion from informational bonus page.

**Comment by KPHowley** [comment]
Created Follow up issue #1071
