### ISSUE TITLE
Update Issue Tracker For Stakeholder meeting 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#892]
### Overview

Update our Issue Tracker for our stakeholder meeting on 8/3 so we have LADOT do MOSCOW priorities on issues.

### Action Items

- [ ] Clear out old issues on tracker
- [ ] verify all issues encompass full descriptions and tags
- [ ] Add all issues to a new issue tracker. 
- [ ] Update issues with status and other information, leaving LA DOT prioritization blank

### Resources

[Issue Tracker](https://docs.google.com/spreadsheets/d/1GmCcqfISkEOArvRxZW2SjHvvVblHGh5ljhbzcaa-I6U/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
This is being closed.  We no longer use this to track issue, but rather the labels and milestones themselves.
