### ISSUE TITLE
Research EPIC: Sidebar Testing

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#936]
### Dependency
- #979
- #1664  

### Overview
We need to identify all the work to be done for the Sidebar usability testing so that we can establish timelines and coordinate the work.

#### Details
Research on conducting sidebar testing for design feature success. This will involve a moderated survey that allows users to see how the process of project creation changes the project level, target points, and points acquired. Users will then be shown 2 different sidebar designs and provide feedback about their preferences related to each design's look and ability to convey the concept of points acquired/target clearly. 

### Action Items
- [x] #2242 
- [x] #2243 
   - [x] Get Research Plan approved by PMs
- [x] #2244 
- [x] #2453 
   - [ ] Run proposed User Testing questions by PMs
- [x] #2245 
   - [x] Conduct UXR Team Training
   - [x] Recruit Interviewees 
   - [x] Schedule Interviews
   - [x] Conduct Interviews
- [x] #2246 
   - [x] FigJam Board
- [x] #2247 
    - [x] Create Presentation of findings from Sidebar Usability Testing for Stakeholders
- [x] #2248 

### Resources/Instructions
- [Wiki Documentation](https://github.com/hackforla/tdm-calculator/wiki/RP012-Test-the-Functionality-of-the-Sidebar)
- [RP012 Research Overview](https://github.com/hackforla/tdm-calculator/wiki/RP012:-Sidebar-Usability-Testing)

**Comment by entrotech** [comment]
@Ebi @bonniewolfe Can we close this Issue?  The dial design was implemented long ago.

**Comment by ExperimentsInHonesty** [comment]
@entrotech This is not about reimplementing it, this issue is about testing to see if it works better than the block design

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard why did you add the ready for product label.  Please detail why in the comment and re-add it if necessary

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard Two items came up while doing a final review of this epic before moving to Done - no PR required

### 2 Wiki pages
https://github.com/hackforla/tdm-calculator/wiki/RP012-Test-the-Functionality-of-the-Sidebar (seems to be the current)
https://github.com/hackforla/tdm-calculator/wiki/RP012:-Sidebar-Usability-Testing

### Action Items
There is no action items spreadsheet in the [wiki](https://github.com/hackforla/tdm-calculator/wiki/RP012-Test-the-Functionality-of-the-Sidebar) so I looked at the RP012 Presentation of Findings: [Round 12 User Testing Insights
Focus: Sidebar Design, Next Steps
](https://docs.google.com/presentation/d/1J8G9o8QUl9TYNschuNcgMvp5e-JefU2pzDUHazL025k/edit?slide=id.g209c25f55ae_0_0&pli=1#slide=id.g209c25f55ae_0_0)

So I recommend you replace the "Action Items Spreadsheet" section that would normally be there (but isn't on this one) with "Next Steps" 

- Change the production site to use the dial design.  - COMPLETED
- Include a demo of the sidebar in application training. 
- Additional post-launch research could be useful to help determine how to make the sidebar in general more noticeable, as this research indicates that novice users did not immediately use the sidebar information to guide their inputs.

**Comment by ExperimentsInHonesty** [comment]
@abbyrivard Please provide update

<details><summary>Instructions</summary>

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
</details> 

You can use this template
```
1. Progress: 
2. Blockers: 
3. Availability:
4. ETA:
5. Pictures (if necessary): 
```

**Comment by abbyrivard** [comment]
@ExperimentsInHonesty completed action requests. Please review changes made on page: https://github.com/hackforla/tdm-calculator/wiki/RP012:-Sidebar-Usability-Testing and let us know if we are okay to re-close this issue

**Comment by abbyrivard** [comment]
> [@abbyrivard](https://github.com/abbyrivard) [@melissaperry09](https://github.com/melissaperry09) There are still two wiki pages. You should delete the one that is no longer the one you want to keep. If you are concerned there might be content on it you didn't move, please re compare them and you can always copy the content of the one you are going to delete to a comment here for final safekeeping.
> 
> > > 2 Wiki pages
> > > https://github.com/hackforla/tdm-calculator/wiki/RP012-Test-the-Functionality-of-the-Sidebar (seems to be the current)
> > > https://github.com/hackforla/tdm-calculator/wiki/RP012:-Sidebar-Usability-Testing

@ExperimentsInHonesty Those 2 pages serve different purposes. One is a RP status page and one is a wiki documentation for a completed RP. On the [Research Plan By Status](https://github.com/hackforla/tdm-calculator/wiki/Research:-Plan:-By-Status) documents, they inform a high level overview of the progress made on an RP. The [Research Plan By Number](https://github.com/hackforla/tdm-calculator/wiki/Research:-Plans:-by-Number) holds all the wiki documentaion for completed RPs with a more fleshed out overview of the entire process and results of the research - would you like us to delete the entire Research Plan by Status page and documentation for all RPs?

**Comment by abbyrivard** [comment]
> > [@abbyrivard](https://github.com/abbyrivard) [@melissaperry09](https://github.com/melissaperry09) There are still two wiki pages. You should delete the one that is no longer the one you want to keep. If you are concerned there might be content on it you didn't move, please re compare them and you can always copy the content of the one you are going to delete to a comment here for final safekeeping.
> > > > 2 Wiki pages
> > > > https://github.com/hackforla/tdm-calculator/wiki/RP012-Test-the-Functionality-of-the-Sidebar (seems to be the current)
> > > > https://github.com/hackforla/tdm-calculator/wiki/RP012:-Sidebar-Usability-Testing
> 
> [@ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) Those 2 pages serve different purposes. One is a RP status page and one is a wiki documentation for a completed RP. On the [Research Plan By Status](https://github.com/hackforla/tdm-calculator/wiki/Research:-Plan:-By-Status) documents, they inform a high level overview of the progress made on an RP. The [Research Plan By Number](https://github.com/hackforla/tdm-calculator/wiki/Research:-Plans:-by-Number) holds all the wiki documentaion for completed RPs with a more fleshed out overview of the entire process and results of the research - would you like us to delete the entire Research Plan by Status page and documentation for all RPs?

After discussion at 2026-04-08 all hands meeting the decision is we need to remove the content on the current Research Plan by Status pages as they stand now. The links on the [Research Plan By Status](https://github.com/hackforla/tdm-calculator/wiki/Research:-Plan:-By-Status) page and [Research Plan By Number](https://github.com/hackforla/tdm-calculator/wiki/Research:-Plans:-by-Number) page should only differ in how they are organized on the page (by status, vs by number). They should both be the wiki documentation for each RP, and the content on the plan by status pages will be combined into one plan by status page as we complete the Research.

**Comment by abbyrivard** [comment]
Made necessary changes to the wiki
