### ISSUE TITLE
Update the TDM summary page

### ISSUE THREAD

**Issue by seenaiype** [hackforla/tdm-calculator#970]
### Overview
To update the Summary page based on the ui design updates #873 

### Action Items

- [ ] Update the TDM summary page based on the UI updates
- [ ] Should work for both logged in and guest users
- [ ] Review it with the PM's

### Resources/Instructions
Final Draft located at **Summary Page** below the 📐 **Draft Pages** in [**Figma**](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4189%3A15774)

![image](https://user-images.githubusercontent.com/88021166/135181844-78441518-887a-4fdf-9125-de9227000632.png)

**Comment by Shaeeka** [comment]
Arrows indicate the components that were updated:

![image](https://user-images.githubusercontent.com/88021166/135725477-8ab6fbde-f441-4f4c-8b18-8b117f66e526.png)

[Summary page in Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4189%3A15775) 

[Summary page in Figma](https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4189%3A16372)

**Comment by fyliu** [comment]
@Shaeeka I have a little bit of time and thought I should just upload my current progress. It's not quite done. I think the spacing looks a little off. Please comment on anything that looks wrong to you when you get a chance.

**Comment by Shaeeka** [comment]
> 
> 
> Update: I'm going to make it display "Yes" and we can talk about it later.
> 
> @Shaeeka What should the NaN text display as? We can make up something and present it at the meeting to see if others like it. I'm thinking just put "Yes" there. Another option is to just hide the whole thing. This may need to be decided by the stakeholder.
> 
> This is the only non-number item so this is a special case we didn't account for before.
> 
> ![2021-10-28 16 05 24 localhost b3189fa35cc5](https://user-images.githubusercontent.com/1160105/139348034-e591e64f-89c8-4862-aa57-aab408793c63.png)

@KPHowley @entrotech please suggest.

**Comment by Shaeeka** [comment]
> 
> 
> @Shaeeka can you tell me about the drop shadows here? I'm not able to extract that information from figma.
> 
> It looks like the box has a shadow to the lower right, maybe 2px with 2px enlargement. Then the text has a shadow straight down maybe 2px. That's from my playing with the numbers to get the general look as the figma. ![2021-10-28 16 15 10 www figma com c71b5d586824](https://user-images.githubusercontent.com/1160105/139348934-2345bf30-9688-4705-93ab-5f030ea2cbf3.png)

@fyliu attached the screen shot of the drop shadow information. (2px 2px 4px) 10%
![image](https://user-images.githubusercontent.com/88021166/140265783-9a2c5ee6-7333-4dcb-9077-f8b82a8af719.png)

**Comment by fyliu** [comment]
There's a few more updates to be made.
