### ISSUE TITLE
Audit Usability Research 1 processes and resources to make a replicable system

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#979]
### Overview
We need to audit and document the resources from the previous Usability Research in order to create templates to use again in subsequent rounds of research

### Action Items
- [x] Add each document from the Wiki to the Audit tab of the spreadsheet and fill out any fields possible
- [x] Review all the issues marked "Issues Used in Setting Research" and identify if templates/checklists or instructions need to be made.
- [x] Clean up Wiki so that its clear what the steps were
- [x] Create a new checklist
- [x] Create templates
- [x] remove dependency on issue #974 

### Resources/Instructions
Wiki | https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-2021-05
Template Folder | https://drive.google.com/drive/folders/1cANLImaVwMcOosJvwc1cGKrB5gJaxs7N
[Spreadsheet for Audit](https://docs.google.com/spreadsheets/d/1u0vfSqVFrSuMMAsEvgZNUfIfjNXdzqJ9VurNV1oGpeU/edit#gid=1785903951)

**Comment by Jane4925** [comment]
Progress: Finalizing Templates 
Blockers: Waiting for feedback from stakeholders on a couple docs; missing template for landing pages (goal of this week) 
Availability: trying to work on it at least a little bit a day!
ETA: Early or Mid Feb

**Comment by Jane4925** [comment]
Progress: Finalizing Discussion Guide and Training Deck; Sorted out sample project confusions, ready for creating landing page template
Blockers: Waiting for feedback from stakeholders(they are coming in... as of today still)
Availability: trying to work on it at least a little bit a day!
ETA: 02/12 ~ 02/19

**Comment by Jane4925** [comment]
Progress: approved volunteer recruitment form, started on documenting tool use for interviews 
Blockers: need Bonnie's help on making template for landing page
Availability: trying to work on it at least a little bit a day!
ETA: 02/19
